### ISSUE TITLE
nil->val replaces falsey things, not just nil

### ISSUE THREAD

**Issue by leifp** [nathanmarz/specter#103]
```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(select [:bool (nil->val true)] {})
;; => [true]
(select [:bool (nil->val true)] {:bool false})
;; => [true]
```

Since 99.9% of the uses of this navigator are to provide default values for missing map keys, this bug is probably very low priority.  But it's an easy fix, so maybe you can save it for a frustrating moment when you need a small thrill of accomplishment.

**Comment by nathanmarz** [comment]
Thanks for the report, it's now fixed in master.
