### ISSUE TITLE
Feature idea: Navigators for transients

### ISSUE THREAD

**Issue by aengelberg** [nathanmarz/specter#106]
Inspired by: https://groups.google.com/forum/?hl=en#!topic/clojure/tFpvQFIwc7A

A suite of navigators that worked on transient collections. Examples:
- `(keypath! :a)` - works on transient maps; uses `assoc!` to transform
- `END!` - uses `conj!` on transient vectors
- `LAST!`, `FIRST!` - uses `assoc!` on transient vectors
- `filterer!` - passes to `next-fn` an immutable filtered sequence, but then uses `assoc!` to insert the filtered results
- `submap!`, `subset!` - return immutable map/set, uses `assoc!` or `conj!` respectively on structure

Do you think something like this would be useful? If so, I'll work on it.

**Comment by nathanmarz** [comment]
Yes, I think having support for navigators would be great. The main design issue that's unclear to me is whether we should have a new set of transient-specific navigators or make the existing navigators also work on transients (via protocols). What are your thoughts on this?

**Comment by aengelberg** [comment]
I would still argue to make the transient navigators separate. From a Clojure philosophy perspective, I would also prefer to have two versions of a function (one immutable, one mutable) rather than have one function that works either way.

Not all the current navigators have an equivalent for transients because Clojure provides very limited options for collections in the transient state. For example, none of the transient collections are `seq`able, so a variety of navigators would be impossible without re-persisting the structures. e.g. `ALL!` would be impossible for transient maps and transient sets, but maybe doable for transient vectors (do a `count` then `nth` on each index). And `BEGINNING!` is impossible for transient vectors. I'm no longer certain that `subset!` is doable in an reasonably efficient way if the argument is very large and the structure is small. `srange!` isn't doable if the subsequence's size changes. This is another potential argument for having separate transient navigators, so it's more clear to the user which navigators are actually supported on transients.

**Comment by nathanmarz** [comment]
OK, this sounds good. Let's move forward with transient-specific navigators.

**Comment by aengelberg** [comment]
I'd like to provide `ALL!`, but it may be confusing to users that it does not work on transient maps and sets (whereas `ALL` works on all persistent collections). Simply adding `!` to make things work on transients wouldn't necessarily just work. What do you think is the best way to handle this particular case? I think renaming it to something else to signify its vector-specificity would be ideal, but I can't think of a good name.

**Comment by nathanmarz** [comment]
`ALL!` seems to be a bit of an odd operation to begin with. I'm not sure if you could do much better than doing `persistent!`, a normal `ALL`, and then `transient` on that result. You might save a roundtrip on doing `persistent!`/`transient` but I don't think that would be very significant.

Additionally, `ALL!` seems to not fit very well with the purpose of transients. Transients are about having a more efficient way to incrementally build up a persistent collection, and there's nothing incremental about `ALL!`. Certainly it makes sense for `ALL` to use transients internally where appropriate, and in the upcoming 0.11.1 it already does that. 

If you do find a sweet spot for `ALL!`, or if the other operations are also type-specific, I think appending "V" for vector operations would jive well with what Clojure already does with `mapv`. So `ALLV!` would be vector-specific. Not sure the same approach would work for lists – `ALLL!` just looks like a typo. A more general approach might be to prepend the name with "V-", "M-","S-", or "L-".

**Comment by aengelberg** [comment]
Good point about `ALL!`. I just used the brand-new benchmarking tools (thanks for those!) to compare `ALL!` on an already transient vector with `ALL` on a persistent vector. The latter was about twice as fast. So I will just not provide `ALL!`.

**Comment by aengelberg** [comment]
Also taking away `filterer!` because it was slower than `filterer` and depended on `ALL!`.

**Comment by nathanmarz** [comment]
Merged for 0.11.1
