### ISSUE TITLE
END could be optimized for vectors

### ISSUE THREAD

**Issue by aengelberg** [nathanmarz/specter#108]
While benchmarking my transient navigators vs the persistent navigators, I noticed the current `END` is very slow on large vectors, because it is doing an `srange` (which I believe involves a concat and then vec) rather than just `conj`ing onto the end.

I whipped up a `NEW-END` which only works on vectors, but it would eventually need to be properly dispatched on type.
```
(defnav NEW-END
  []
  (select* [this structure next-fn]
    (next-fn []))
  (transform* [this structure next-fn]
    (into structure (next-fn []))))

(let [v (vec (range 1000))]
  (run-benchmark "END on large vector"
    6 1000
    (setval [END] [1] v)
    (setval [NEW-END] [1] v)))

********************************
Benchmark: END on large vector

Avg(ms)		vs best		Code
0.72255 		 1.00 		 (setval [NEW-END] [1] v)
186.05 		 257 		 (setval [END] [1] v)

********************************
```

**Comment by nathanmarz** [comment]
The same is true of BEGINNING on lists, which can just use `cons`.

**Comment by nathanmarz** [comment]
Should be easy to do by dispatching with a protocol inside the implementation like how `ALL`, `FIRST`, and `LAST` work.

**Comment by nathanmarz** [comment]
Done for 0.11.1
