### ISSUE TITLE
Filtering using functions

### ISSUE THREAD

**Issue by addywaddy** [nathanmarz/specter#11]
Not sure if this is the right channel for general questions regarding the usage of specter, so please point me in the right direction if not. I have the following hashmap that I'd like to navigate:

```clojure
(def store {"foo" {[1 2] {:value 1} [2 3] {:value 2} [3 4] {:value 3}}})
```
Specifically, I'd like to get all values where the key includes a specific number, and saw that functions can also be used as filters:

```clojure
(defn my-selector [number record]
  (some #{number} (flatten (keys record))))
```
However, the results are not as I expected:
```clojure
(select ["foo" (partial my-selector 2) :value] store)
;; => [nil]
(select ["foo" (partial my-selector 2)] store)
;; => [{[2 3] {:value 2}, [3 4] {:value 3}, [1 2] {:value 1}}]
```

Any pointers as to where I'm going wrong would be much appreciated.

**Comment by nathanmarz** [comment]
String don't implement the StructurePath protocol, so they can't be used directly as selectors like that. Instead, do this:

```clj
(select [(keypath "foo")
             ALL
             (selected? FIRST ALL #(= 2 %))
             LAST
             :value]
   store)
```

You could also do it by putting the entire `selected?` clause in a custom function like you did, but this is cleaner in my opinion.
