### ISSUE TITLE
Enable ALL to remove elements

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#117]
If NONE is returned by the transform-fn, then don't add the element to the returned collection. This is a commonly requested use case and this method is much faster than previously mentioned `ALL-ELEM-SEQ`.

**Comment by aengelberg** [comment]
Maybe add a new navigator `OMIT` (or a better name) which returns `s/NONE` when selecting and transforming (compared to `STOP` which only returns it when selecting).

**Comment by aengelberg** [comment]
Similarly, `keypath` could dissoc the key if the transformer comes back with `NONE`.

Example use case:
```
;; increments all numbers in key :x, but dissoc's the key if the collection is empty
;; in:  [{:x []} {:x [1]} {:x [1 1]}]
;; out: [{} {:x [2]} {:x [2 2]}]
(transform [:x (if-path #(> (count %) 0) STAY OMIT) ALL] inc my-data)
```

**Comment by nathanmarz** [comment]
They `keypath` change is a good idea – we'd have to make it work for sequences too. Not sure about `OMIT` though since that seems to be conflating transformation with navigation. I was thinking of something like this for usage:

```clojure
(setval [ALL even?] NONE [1 2 3 4])
;; => [1 3]
```

Probably the best place to discuss/brainstorm would be the #specter channel on Clojurians.

**Comment by nathanmarz** [comment]
I have some serious reservations about this feature idea now. Been doing some deep investigation into how the `locate` feature would work, specifically:

1. Suppose you do `(locate ALL [1 2 3 4 5 6 7])`. Then the locations are 0, 1, 2, 3, 4, 5, 6
2. Now suppose you do `(setval [(srange 0 2) ALL] :a)`. 
3. A very natural and desirable capability is an efficient way to incrementally update the previously computed locations. You want to know which locations have changed values, which locations are now invalid, and what the new locations are. In this case only indices 0 and 1 have changed.
4. With some basic static metadata about the navigators, you can determine that `[(srange ...) ALL]` will only affect subvalues restricted by the substructure of the `srange`. However, this is **only** the case if `ALL` cannot add or remove subvalues. This is a big efficiency boost because you can know statically that indices 2 through 6 can be ignored in the incremental locations update.

This use case shows that adding the removal feature to `ALL` has huge implications as to the efficiency of an incremental locations algorithm.

One possibility is to have another version of `ALL` with this additional capability along with more metadata to assist an incremental locations algorithm. I'm not yet sure whether this should be the approach or whether subvalue navigators should be restricted from adding or removing subvalues.

**Comment by nathanmarz** [comment]
Started this on `remove-with-none` branch. `PersistentArrayMap` case is tricky since don't know ahead of time what the size of the array should be. Considering doing a solution where it copies the array at end to a smaller size if any NONE's were encountered.

**Comment by nathanmarz** [comment]
Implemented in master. For the time being chose not to implement this for `keypath`/`must` for removing from vectors.
