### ISSUE TITLE
Expose traverse to be reducible alternative to select

### ISSUE THREAD

**Issue by aengelberg** [nathanmarz/specter#118]
`traverse` would behave like `select` but returns a reducible object.

```
(reduce conj #{} (traverse [ALL :a] [{:a 1} {:a 2}]))
=> #{1 2}
```
Presumably more efficient than using `select` when you know you don't want a vector returned.

**Comment by nathanmarz** [comment]
Implemented this in the traverse branch. Benchmark looks really good:

```
Benchmark: Traverse into a set

Avg(ms)		vs best		Code
657.24 		 1.00 		 (set data)
695.33 		 1.06 		 (persistent! (reduce conj! (transient #{}) (traverse ALL data)))
771.74 		 1.17 		 (set (select ALL data))
1088.9 		 1.66 		 (reduce conj #{} (traverse ALL data))
```

**Comment by nathanmarz** [comment]
Using `into` it's very elegant:

```
Benchmark: Traverse into a set

Avg(ms)		vs best		Code
654.42 		 1.00 		 (set data)
685.68 		 1.05 		 (persistent! (reduce conj! (transient #{}) (traverse ALL data)))
686.09 		 1.05 		 (into #{} (traverse ALL data))
768.11 		 1.17 		 (set (select ALL data))
1086.3 		 1.66 		 (reduce conj #{} (traverse ALL data))
```

**Comment by nathanmarz** [comment]
Some further ideas to brainstorm:

- Parallel traversal
- Stateful navigators: transducers can do things like "take only the first 3 elements traversed". No idea if this fits into Specter's abstractions or whether this can be done efficiently. 
- Is there a way to unify Specter with transducers? There's a lot of overlap now in the use cases.

**Comment by nathanmarz** [comment]
Merged into master
