### ISSUE TITLE
Add "safe" versions of select and select-one

### ISSUE THREAD

**Issue by luxbock** [nathanmarz/specter#123]
There's a pretty common sentiment that `safe-get` and `safe-get-in`, i.e. versions of `get` and `get-in` that throw an exception instead of `nil` for when no value is found, should be included in `clojure.core`. Since `specter` is already such a good alternative to never using those two, it would be nice if it fixed this annoyance by providing versions of `select` and `select-one` that behave in this manner.

**Comment by nathanmarz** [comment]
I think you're looking for [select-one!](http://nathanmarz.github.io/specter/com.rpl.specter.macros.html#var-select-one.21)?

**Comment by luxbock** [comment]
`(select-one! [:foo :bar] {:foo {:baz 1}})` => `nil`

What I'm looking for is:

`(safe-select [:foo :bar] {:foo {:baz 1}})` => Exception

**Comment by nathanmarz** [comment]
If you use `must` in conjunction with `select-one!` you'll get the behavior you're looking for.

```clojure
(select-one! [(must :foo) (must :bar)] {:foo {:baz 1}})
```

**Comment by luxbock** [comment]
How would I write a safe version of the following using `specter`?

`(safe-get-in {10 {20 "treasure"}} [10 30])` => Exception

**Comment by nathanmarz** [comment]
```clojure
(select-one! [(must 10) (must 30)] {10 {20 "treasure"}})
```

**Comment by luxbock** [comment]
Ah sorry, that was rather obvious. I now see the point of `select-one!` vs. `select-one`.
