### ISSUE TITLE
Two namespaces is awkward

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#124]
It's awkward to have to require both `specter` and `specter.macros`, especially if you use qualified namespaces:

```clojure
  (:require [com.rpl.specter :as s]
                [com.rpl.specter.macros :as sm]))
```
Could I suggest the true functions have the names shown in the README? (I'm curious why `transform` etc. became macros?)

**Comment by nathanmarz** [comment]
The two namespaces thing is done for ClojureScript compatibility, where macros have to be in a separate namespace.

For my own projects, I use [Potemkin](https://github.com/ztellman/potemkin/blob/master/src/potemkin/namespaces.clj) along with the following function to get everything into a single namespace.

```clojure
(defn import-namespace [ns-sym]
  (require ns-sym)
  (let [ns (the-ns ns-sym)]
    (doseq [[sym v] (ns-publics ns)]
      (import-var v)
      )))
```

The core operations became macros to enable the inline factoring and caching feature, which lets Specter run with very high performance without explicit precompilation. Explained in detail here: https://github.com/nathanmarz/specter/wiki/Specter-0.11.0:-Performance-without-the-tradeoffs

**Comment by marick** [comment]
Grr. Clojurescript. 

I also use Potemkin and also have [wrappers](http://marick.github.io/suchwow/such.immigration.html). I think I'll just use `use` for the book (which I've resumed, having quit my job).

**Comment by nathanmarz** [comment]
Ah cool. A lot has changed since you started writing it, let me know if you need any feedback/guidance.
