### ISSUE TITLE
Integrate with transducers

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#125]
Example: `(traverse [:a :b :c])` should make a transducer

For this to work, a new requirement would have to be added to the `select*` path of `Navigator` to properly handle `reduced?`. This is related to #121

**Comment by aengelberg** [comment]
What would such a transducer do exactly? Would it behave like (map (partial select ...)) or (mapcat (partial select ...))? If you haven't decided yet, I'd argue for the latter.

**Comment by nathanmarz** [comment]
It would do whatever is most natural (and thereby most efficient) which I believe would correspond to the latter.

**Comment by nathanmarz** [comment]
`traverse-all` would be a better name (suggested by @aengelberg)

**Comment by aengelberg** [comment]
Other name idea: `selectcat` (because it's equivalent to `(mapcat select)`)

**Comment by nathanmarz** [comment]
`ALL`, `MAP-VALS`, `continuous-subseqs`, and `multi-path` are all the built-in navigators that would need to to check `reduced?` They all use `doseqres` which uses `reduce` already, so all that's needed by a `traverse-all` implementation is for the continuation function to always return the current reduced val. If it is wrapped in `reduced`, that will cause all traversal to stop.

I don't believe recursive paths require any other special handling of `reduced?`, but that should certainly be tested.

**Comment by aengelberg** [comment]
If you get all the navigators handling "reduced" properly, will you get a
fast "select-first" for free?

I wonder what the performance cost of calling "reduced?" at every element
will be.

**Comment by nathanmarz** [comment]
Yes, this will give a fast `select-first`. It technically won't be as fast as a specialized code path (because of checking of `reduced?`, but I don't think the overall difference will be that substantial.

The current implementation is already paying the cost of `reduced?`. The benchmark that shows the difference at the moment is this one: https://github.com/nathanmarz/specter/blob/master/scripts/benchmarks.clj#L116 `map-vals-iterable` does not check `reduced?`, while `reduce-kv` does. The difference is less than 10% in that one. 

One last thing – my last comment was inaccurate as `reduce` will automatically deref reduced vals. So if `doseqres`  encounters a `reduced?` val it must wrap it again in `reduced`. Then, at the top-level, `reduced?` vals should be dereferenced.

**Comment by nathanmarz** [comment]
This work is started in the early-terminate branch.

**Comment by nathanmarz** [comment]
Implemented in master.
