### ISSUE TITLE
Add more examples with nested maps

### ISSUE THREAD

**Issue by vspinu** [nathanmarz/specter#127]
The docs are almost exclusively concerned with vectors.  I am having a real strugle with the nested maps at the moment. 

First, the following works but I would like to keep only matched elements and all my attempts with `filterer` failed. 

 ```clojure
(sp/transform [ALL (fn [[k v]] (:id v))]
              (fn [[k v]] [k :new])
              {:a {:id 1} :b {:kk 2}})
;; {:a :new, :b {:kk 2}}
```
I would like to see `{:a :new}` as a result. 

Second, I was expecting the  shorter version to work as well

```clojure
(sp/transform [ALL :id]
              (fn [[k v]] [k :new])
              {:a {:id 1} :b {:kk 2}})
```

but it gives ` Key must be integer` error. 

What am I missing here? Thanks.

**Comment by aengelberg** [comment]
The key concept

**Comment by aengelberg** [comment]
The key concept I think you're missing is that when doing a "transform", if items are not navigated to (because predicates fail), they are not removed from the result, but just untouched.

**Comment by aengelberg** [comment]
Filterer won't help here either, because the values unmatched by the predicate will still appear, untouched, in the output structure.

When #117 is resolved there will be a more elegant way to omit values as a part of a transform.

**Comment by vspinu** [comment]
So is there a way at all to omit untouched elements at all? Or we all have to wait till #117 is fixed?

**Comment by nathanmarz** [comment]
If all you want is the matched elements, then just use `select`:

```
(->> {:a {:id 1} :b {:kk 2}}
     (select [ALL (selected? LAST (must :id))])
     (into {})
     (setval MAP-VALS :new))
```

There's nothing to "fix" with #117, it would be a completely new feature. I'm not sure yet about whether adding the feature is the right thing to do.

**Comment by vspinu** [comment]
> then just use select:

I see. It's a bit on a verbose side and I have a feeling that such manual reconstruction won't play well with multi-level maps.

If "select -> manually re-constructing the map" is idiomatic specter then I have no complains.  It's surprising though that specter does not provide "structure preserving" selects. IMHO it's a very useful feature and it would naturally complement existing functionality by doing `transform` and `select` in one blow.

**Comment by nathanmarz** [comment]
There's two ways to look at this. One is selecting what you need and then manipulating it as necessary, the other is to look at this as doing two separate transformations: first to replace map vals with `:id` keys with `:new`, and the second to remove map entries that don't have :id keys. With #117 the latter strategy would look like:

```clojure
(transform MAP-VALS
  (fn [m] (if (contains? m :id) :new NONE))
  data)
```

It just happens to be in this case that both transformations could be specified concisely by a single transformation function.
