### ISSUE TITLE
Preserving array maps in transform

### ISSUE THREAD

**Issue by siphiuel** [nathanmarz/specter#137]
Hi,

first of all - thanks for a great library!

Just today i've noticed that transform does not preserve array maps. Meaning:

```
(def m (apply array-map 0 20)) ; just a bit more of the implicit threshold for array/hash maps
(type m) ; clojure.lang.PersistentArrayMap
(def transformed-m (transform [MAP-VALS] inc m)
(type transformed-m) ; clojure.lang.PersistentHashMap
```

Is this an expected behaviour, or something that can be resolved?

Thank you!

**Comment by nathanmarz** [comment]
I didn't even realize it was possible to create a PersistentArrayMap above the threshold. Looks like this should be fixable – out of curiosity, what's your use case for a PersistentArrayMap above the threshold?

**Comment by nathanmarz** [comment]
Fixed in master. Turns out the fix for this improved the performance of MAP-VALS on PersistentArrayMap by about 2x.

**Comment by siphiuel** [comment]
Thanks for quick response!

My use case is this: a graph of functions is constructed with help of https://github.com/stuartsierra/dependency. Each function body is dynamically `eval`d. The graph contains function names only, other useful metadata (body etc.) are contained in a map.

In order for the evaluation of all functions to succeed, i have to make sure that each function has all its dependency functions evaluated earlier. Therefore, the nodes in the graph are sorted topologically (via `dep/topo-sort`), and the aforementioned map is an array map created after this sorting.

As i wrote this, it became obvious thata seq of topologically sorted nodes could be used alongside a usual hash map in order to perform ordered evaluation, but somehow the implementation evolved in a different way - it seems a bit more convenient to have a single properly ordered map.

Another cool thing is that this graph is then traversed by a Storm bolt. So i am quite a heavy user of your projects!

Thank you for your work.
