### ISSUE TITLE
comp-paths doesn't appear to do what the documentation says

### ISSUE THREAD

**Issue by Engelberg** [nathanmarz/specter#150]
According to the docs, any missing parameter turns the compiled path into a function expecting that parameter.  But I am getting the following error:

```clojure
=> (let [counter-path (comp-paths keypath (nil->val 0))]
     (counter-path :counter))
ClassCastException com.rpl.specter.impl$combine_two_navs$reify__22597 cannot be cast to clojure.lang.IFn  logic-master.sat/eval39241 (form-init8538157656751328577.clj:2)
```

**Comment by nathanmarz** [comment]
Updated the docstring as that feature no longer exists as of 0.13.0. In 0.13.0, just use `path`:

```clojure
(defn counter-path [key]
  (path (keypath key) (nil->val 0)))
```

Since `path` does inline caching, this will run extremely fast.

**Comment by Engelberg** [comment]
It's not the docstring where I found this info.  It was here:
https://github.com/nathanmarz/specter/wiki/List-of-Navigators#comp-paths
