### ISSUE TITLE
Specter fails with newer cljs versions

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#152]
This repo reproduces the problem: https://github.com/darwin/pesky-select-star

This is a new issue with 0.13.x so likely has something to do with the new inline caching implementation.

**Comment by nathanmarz** [comment]
Was able to reproduce with `(multi-path STAY STAY)`

**Comment by nathanmarz** [comment]
The problem had something to do with a change in how ClojureScript decides to use a macro or a function if both are defined in same namespace. Not sure exactly, but updated the macros for exec-select* and exec-transform* to generate cljs-compatible code if in cljs environment.

**Comment by darwin** [comment]
Fixed!

We are green: https://travis-ci.org/binaryage/dirac/builds/167658548
