### ISSUE TITLE
Use akhudek/fast-zip?

### ISSUE THREAD

**Issue by alexandergunnarson** [nathanmarz/specter#153]
This looks like a really cool and useful library! One thing I was wondering — I see you're using clojure.zip. Have you taken a look at https://github.com/akhudek/fast-zip ? It's quite a bit faster than clojure.zip (or at least it was at the time of its benchmarks) due to its use of `deftype`. Just a thought for your consideration.

Keep up the great work!

**Comment by nathanmarz** [comment]
The zipper integration in Specter is only rarely needed. Almost all cases can be handled by the built-in navigators or simpler custom navigators. The integration is there more to show that zipper-based operations can be encapsulated by Specter's API. For that reason it's not worth adding another dependency to Specter.
