### ISSUE TITLE
How to use `implicit-nav` with a record (converting 0.11 -> 0.13)

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#154]
For Reasons (let's assume they're good for now), https://github.com/marick/structural-typing has its own rules for traversing paths composed of core types like keywords. It does not stomp on the built-in Specter behavior (because people use both Specter and the library). Instead, it transforms a path like `[:b odd?]` into:

``` clojure
[ (->KeywordPathElement :b) (->PredicatePathElement odd?) ]
```

... and then applies `select` (say) to that and the structure to be traversed.

The old implementation was this:

```
(defrecord KeywordPathElement [key-given-in-path])

(extend-type KeywordPathElement
  sp/Navigator
  (select* [& args] (apply associative-select* args))
  (transform* [& _] (no-transform!)))
```

I can't find anything in https://github.com/nathanmarz/specter/wiki/List-of-Macros that seems to fit this case. Because `associative-select`'s behavior can depend on both keywordpath and the value of the element being examined, using the `ImplicitNav` protocol isn't right. `RichNavigator` looks better, but I haven't had luck with it. For example, given this:

``` clojure
(extend-type KeywordPathElement
  RichNavigator
  (select* [this vals structure next-fn]
    (this structure))
  (transform* [args] nil))
```

... I get `Not a navigator: #user.KeywordPathElement{:key-given-in-path :b}` even though an instance `satisfies?` `RichNavigator`. And, even if this worked, it's evading the documented interface. 

So: how to use a record as a path element?

**Comment by nathanmarz** [comment]
Use `defnav` to define the navigators:

```clojure
(defnav keypath-elem-nav [k]
  (select* [this structure next-fn]
    (associative-select* k structure next-fn))
  (transform* [this structure next-fn] (no-transform!)))
```

Then extend `ImplicitNav` on your record type:

```clojure
(extend-protocol ImplicitNav
  KeywordPathElement
  (implicit-nav [this] (keypath-elem-nav (:key-given-in-path this))))
```

You can also skip all the implicit nav stuff and wrap the elements of your path directly in these custom navigators, e.g.:

```clojure
[(keypath-elem-nav :b) (predicate-elem-nav odd?)]
```

**Comment by marick** [comment]
Thanks. A few things that I noticed that might have a place in the documentation.

1. In a `defnav` statement like your above:

```clojure
(defnav keypath-elem-nav [k]
  (select* [this structure next-fn]
    (associative-select* k structure next-fn))
  (transform* [this structure next-fn] (no-transform!)))
```

`this` is not the path element you're working with. (I'm not sure what it is.) In my code, I used these names:

```clojure
(specter/defnav always-five [this]
  (select* [_unusable structure next-fn] ...)
```

2. It's worth noting that the `defnav` argument lists aren't full clojure arglists. I needed to convert:

```clojure
         (transform* [& _] (no-transform!))
```

... to:

```clojure
         (transform* [_this _structure _next-fn] (no-transform!)))
```

3. Unlike in 0.11, functions can't just return instead of calling the continuation. I had `select*` functions that immediately returned, as in:

```clojure
(cond (nil? leaf-value) 
      ;; The following will work
      (next-fn (update-exval exval {:conj-path original-key
                                          :descend-into nil}))

      ;; This will NOT work
      (not (map? leaf-value))
      (errcase explain/oopsies:not-maplike exval {:conj-path original-key})
```

Those fail. More simply, something like:

```clojure
(specter/defnav keypath-elem-nav [keyholder]
  (select* [this structure next-fn]
     3)      ;; I used this a lot for quick short-circuiting upon detecting bad structure.
```

... will always produce the empty list, not a list containing 3. To produce the latter, you *must* do this:

```clojure
(specter/defnav keypath-elem-nav [keyholder]
  (select* [this structure next-fn]
     (next-fn 3))
```

**Comment by nathanmarz** [comment]
The `this`parameter is currently a placeholder, but is meant to refer to the navigator object. That may be implemented in the future.

`defnav` does some trickery with the declared names in order to make value collection work seamlessly, which is why you have to enumerate all the arg names. 

0.12.0 changed the contract of how `select*` works in order to enable huge performance improvements. Deviating from the contract will produce unexpected results. If you want to do something like take an alternate codepath when you detect something "bad", I recommend using `if-path` for that, e.g.:

```clojure
(select [ALL
             (if-path bad-structure?
                (view (fn [_] :BAD-VAL)) 
                <normal navigation here>)] 
  structure)
```

You can use dynamic navigators to encapsulate this into its own abstraction:

```clojure
(defdynamicnav fork-bad [& path]
  (if-path bad-structure? (view (fn [_] :BAD-VAL)) path))

(select [ALL (fork-bad <normal navigation here>)] structure)
```
