### ISSUE TITLE
annotating values of a selection with their absolute specter paths

### ISSUE THREAD

**Issue by drorbemet** [nathanmarz/specter#156]
**annotating values with their absolute paths**
*Example1 - an absolute path specifying a child element in a tree of maps:*
=> (select [a path e.g. ALL even?] {:a {:b 2} {:c 3}})
{:path [:a :b] :val 2}

=> (setval [:a :b] 4 {:a {:b 2} {:c 3}})
{:a {:b 4} {:c 3}}

*Example2 - an absolute path specifying a position in a vector:*
=> (select [a path e.g. ALL even?] [0 1 2 3 4 5])
[{:path {:pos 0} :val 0} 
{:path {:pos 3} :val 2}
{:path {:pos 4} :val 4}]

=> (setval {:path {:pos 4} :val 4} :update [0 1 2 3 4 5])
[0 1 2 3 :update 5]

Would specter lend itself to use cases in which paths are returned as annotation of a selection for later use in explicit calls to e.g. update one specific value?

How could absolute paths be represented to the user of specter?
Is there already a usable representation of absolute paths within the implementation of specter?

How could this option to annotate values with their absolute paths be seamlessly integrated with the existing specter navigators and macros?
Would the cost of implementation for this in specter be relatively low or high?

**Motivation for absolute paths in specter**
Editing large clojure data structures manually.
(similar to search edit write operations in emacs like occur and others)

1. Selecting specific elements within a large data structure and printing them into a text buffer or text file.
2. Editing each element of the selection manually.
3. Merging the selection with it's changed values back into the large data structure.

**Comment by nathanmarz** [comment]
You're looking for a `locate` feature, for which there is already issue #49 open. Best to take the discussion there.
