### ISSUE TITLE
The example of cond-path seems wrong

### ISSUE THREAD

**Issue by luminusian** [nathanmarz/specter#158]
Currently,
=> (select [ALL (cond-path (must :a) :a (must :b) :c)] [{:a 0} {:b 1} {:c 2}])
[0 2]

Actually,
=> (select [ALL (cond-path (must :a) :a (must :b) :c)] [{:a 0} {:b 1} {:c 2}])
[0 nil]

**Comment by nathanmarz** [comment]
Thanks, it's fixed.
