### ISSUE TITLE
No longer works with Clojure 1.6

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#16]
That seems premature?

**Comment by nathanmarz** [comment]
Oh, this is likely because of making use of .cljc files for combined Clojure/ClojureScript compatibility. Probably the best thing to do would be to find a way to package the jar with ,clj and .cljs files instead of .cljc files.

**Comment by mstang** [comment]
Has anyone backported this to 1.6.0?

**Comment by nathanmarz** [comment]
This is available in master and will be released for 0.8.0

**Comment by mstang** [comment]
In order to make sure I could use Specter, I spent five hours and upgraded
all of my libraries to Clojure/ClojureScript 1.7 and the latest version
(pre-next) of Om.

**Comment by nathanmarz** [comment]
@mstang Just before you posted that comment I released 0.8.0 which is compatible with 1.6 :)
