### ISSUE TITLE
Exception on `providepath` during aot compiling

### ISSUE THREAD

**Issue by caioaao** [nathanmarz/specter#160]
Declaring a path on two different namespaces makes the project throw `java.lang.ClassCastException: com.rpl.specter.impl.CachedPathInfo cannot be cast to com.rpl.specter.impl.CachedPathInfo` when calling `lein uberjar`.

I've created a repository to reproduce the error: https://github.com/caioaao/specter-reproduce
There is one path declaration:

In `specter-reproduce.core-path`:
```clojure
(sp/declarepath map-walker)
(sp/providepath map-walker
                 [(sp/walker map?)
                  (sp/continue-then-stay sp/MAP-VALS map-walker)])
```

When declared on `core.clj`, the exception doesn't occur, which points to a problem during aot compile, as `core` ns  has `^:skip-aot` meta on `project.clj`.

The complete output when running `lein uberjar` is [here](https://gist.github.com/caioaao/2aef8e893bf1e3b7b5b099abc3798028).

Reproduced on `0.13.1` and `0.13.2-SNAPSHOT`. Couldn't reproduce it on `0.12.0`.

**Comment by caioaao** [comment]
Updated the issue with new info. I was wrong and it actually happens with a single recursive step declaration.

**Comment by akond** [comment]
I got the same error when tried to use `:jvm-opts ["-Dclojure.compiler.direct-linking=true"]` in `project.clj`
