### ISSUE TITLE
I can't make this example work with clojurescript (figwheel)

### ISSUE THREAD

**Issue by toreohm** [nathanmarz/specter#164]
With clojure using REPL works fine:
`(def data {:a [1 2 3]}) ` 
`(S/setval [:a END] [4 5] data)`
=> **{:a [1 2 3 4 5]}**

but with clojurescript using figwheel it gives me this warning:
`(def data {:a [1 2 3]}) ` 
`(S/setval [:a END] [4 5] data)`

cljs.user=> (S/setval [:a END] [4 5] data)
WARNING: Use of undeclared Var cljs.user/END at line 1 <cljs repl>
**{:a [4 5]}** <---- different result

How can I make it work correctly using clojurescript? ?

**Comment by nathanmarz** [comment]
`END` is in the `com.rpl.specter` namespace, so I'm guessing you just need to do `(S/setval [:a S/END] [4 5] data)`?

**Comment by toreohm** [comment]
Thankyou for your help!!
