### ISSUE TITLE
sample code for comp-paths fails

### ISSUE THREAD

**Issue by freakhill** [nathanmarz/specter#167]
the example

```
(let [param-path (comp-paths :a :b keypath))]
     (compiled-transform (param-path :c) inc {:a {:b {:c 0, :d 1}}})
```

fails with

`ClassCastException com.rpl.specter.impl$combine_two_navs$reify__15234 cannot be cast to clojure.lang.IFn`

with clojure 1.9 alpha14 and specter 0.13.2

**Comment by nathanmarz** [comment]
As of 0.13.0 compiling without parameters is no longer necessary or supported. The examples on the wiki have been updated.
