### ISSUE TITLE
Add a transform-indexed?

### ISSUE THREAD

**Issue by LispEngineer** [nathanmarz/specter#169]
Hi there,

([See also this item.](https://github.com/boxed/instar/issues/20))

Would it be possible to have a `transform-indexed` in Specter that provides to the transformer function the path to the current item being transformed, as well as its value? This would be akin to the standard Clojure `map-indexed`.

For example:

```clojure
(def x {:objects
   {:a {:type :npc :script "a.script"} 
    :b {:type :object :script "b.script"} 
    :c {:script "c.script"} 
    :npc {:script "d.script"}}})
```

I'd like to be able to call something like:

```clojure
(transform-indexed [:objects MAP-VALS :type] (fn [index val] (some-func index val)) x)
```

which is very closely akin to:

```clojure
(transform [:objects MAP-VALS :type] (fn [val] (some-func val)) x)
```

(Yes, I know the `(fn [...` syntax is silly, but the point was to emphasize the number and purpose of the arguments to the transformer function.)

The calls to the inner `fn` in the indexed example would be:

* `[:objects :a :type]` and `:npc`
* `[:objects :b :type]` and `:object`
* `[:objects :c :type]` and `nil`
* `[:objects :npc :type]` and `nil`

Is this already possible in some way? If not, could something like this be added, please?

Thanks for Specter!

**Comment by nathanmarz** [comment]
You can already do this using value collection. For example:

```clojure
(transform [:objects ALL (collect-one FIRST) LAST] (fn [k val] ...) data)
```

`k` in your example data would resolve to `:a:, `:b:, `:c:, and `:npc`. 

You can also use value collection with recursive paths to achieve the same goal for more involved use cases.

**Comment by LispEngineer** [comment]
@nathanmarz Thank you for the super quick reply and, even better, a solution. I will add this to your Wiki!

**Comment by LispEngineer** [comment]
It appears I cannot edit the wiki, @nathanmarz. As such, I provide a working example here for you to add to your wiki, such that others can learn.

Add a default `:type` to each innermost map that does not have one, whose value is either `:object` or `:npc`. `:npc` will be assigned only if the key of the enclosing map is `:person`.

```clojure
core=> (def x {:objects
   {:amulet {:type :equipment :script "amulet.script"} 
    :box {:type :container :script "box.script"} 
    :chest {:script "chest.script"} 
    :person {:script "dreamer.script"}}}) 
#'core/x
core=> (pprint (transform [:objects ALL (collect-one FIRST) LAST] (fn [k val] (if (:type val) val (assoc val :type (if (= :npc k) :npc :object)))) x))
{:objects
 {:amulet {:type :equipment, :script "amulet.script"},
  :box {:type :container, :script "box.script"},
  :chest {:script "chest.script", :type :object},
  :person {:script "dreamer.script", :type :object}}}
nil
core=>
```

**Comment by nathanmarz** [comment]
@LispEngineer This example is more complicated than what already exists for docs for `collect` and `collect-one` and doesn't seem to add any more insight. 

To filter out maps without a `:type` key, you can put `(not-selected? (must :type))` before the `ALL`.
