### ISSUE TITLE
Making paths available to callers of `select`.

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#17]
https://github.com/marick/structural-typing/ uses Specter to allow a sort of type checking, where types can be described like this:

```clojure
(type! :Example {[:x ALL :y ALL] [integer?]})   ; there's a non-side-effecting version too
```

When producing a type error, I display the path (as above). I'd like to display it like so:

```clojure
[:x ALL :y ALL][2,3] should be `integer?`; it is `"2"`
```
... which would identify which particular element of the nested structure is wrong. As it is, the best I can do is to display `[:x ALL :y ALL][6]` and let the user figure out which is the 6th leaf in the structure being checked.

I'd like to do some magic lifting-style stuff where the path gets passed along, state-monad-like, for the delectation of clients who want more than just the leaf value. But I'm not smart enough to see it, if indeed it's there to be seen.

If I'm pointed to a clever twist, I'll do the scut work of implementing and documenting it.

**Comment by nathanmarz** [comment]
If you put VAL in between all elements of your path, like [VAL :x VAL ALL VAL :y VAL ALL] then you'll get the path in the output of select or given as arguments to the update-fn for transform. Does this help?

**Comment by marick** [comment]
Clever. I think this is what I need.

**Comment by marick** [comment]
Although... things get awkward with paths that include predicates:
```clojure
user=> (select [VAL ALL even?] [1 2 2 1 2])
[[[1 2 2 1 2] 2] [[1 2 2 1 2] 2] [[1 2 2 1 2] 2]]
```

Hard to assign indices without re-evaluating the predicates.

Now imagine deep nesting (including empty arrays) and predicates that apply to arrays:

```clojure
user=> (pprint (select [VAL ALL #(> (count %) 2) VAL ALL even?] [ [] [1] [1 2] [1 2 3] [1 2 3 4]]))
[[[[] [1] [1 2] [1 2 3] [1 2 3 4]] [1 2 3] 2]
 [[[] [1] [1 2] [1 2 3] [1 2 3 4]] [1 2 3 4] 2]
 [[[] [1] [1 2] [1 2 3] [1 2 3 4]] [1 2 3 4] 4]]
```

Deducing paths after the fact is looking less good, compared to recording paths as they're taken.

Hmm...

**Comment by nathanmarz** [comment]
So you want to capture the indices into a sequence whenever ALL is used? Do something like this:

```clojure
(defn indexed [aseq]
  (map-indexed vector aseq))

(def ALL-WITH-INDEX-VAL [(view indexed) ALL (collect-one FIRST (view #(str "Index: " %))) LAST])
```
Of course, while ALL works on maps and sets, this only makes sense for sequences.

**Comment by marick** [comment]
Yes, that works. `view` is nice. Thanks.
