### ISSUE TITLE
String navigation

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#170]
It would be nice if navigators like `srange`, `ALL`, `FIRST`, and `LAST` worked on strings. For example:

```clojure
(setval (srange 1 3) [] "abcde")
;; => "ade"
```

**Comment by nathanmarz** [comment]
An open question is whether srange should navigate to a string or to a sequence of characters, or whether there should be a string-specific srange which navigates to a substring.

**Comment by nathanmarz** [comment]
`END` and `BEGINNING` could also work with strings, and it's an open question whether it should navigate to `""` or to `[]`.

**Comment by aengelberg** [comment]
I would encourage `srange`, `END` and `BEGINNING` have consistent behavior as on collections, from the perspective of later navigators.

**Comment by nathanmarz** [comment]
Implemented in master by extending `srange`, `END`, `BEGINNING`, `FIRST`, and `LAST` to strings
