### ISSUE TITLE
Nested stringified keys

### ISSUE THREAD

**Issue by JoePython1** [nathanmarz/specter#171]
I am still trying to get a grip on this library.
How to select a nested string key 

`(def x {"a" {"info" {"version" 1}}, 
            "b" {"info" {"version" 2}}})`

I am expecting to get the version information for the string keys "a" and "b"
`{ "a" 1 , "b" 2}`

**Comment by nathanmarz** [comment]
There's two approaches. The first is to select the values for the keys you want and get a vector back:

```clojure
(select [(multi-path (keypath "a") (keypath "b")) (keypath "info" "version")] x)
;; => [1 2]
```

The second is to transform the map into one from key -> version:

```clojure
(transform MAP-VALS
  (fn [m] (select-any (keypath "info" "version") m))
  x)
;; => {"a" 1, "b" 2}
```

**Comment by JoePython1** [comment]
Your second was very appropriate. 
The following also worked for me 
`;;(select [ALL
;;            (collect-one FIRST)
;;            LAST
;;            (keypath "info" "versionl")] x)
`
