### ISSUE TITLE
SubVectors get transformed into LazySeq's

### ISSUE THREAD

**Issue by rauhs** [nathanmarz/specter#180]
See:

```clojure
(class (compiled-transform (comp-paths LAST) inc (subvec [0] 0)))
```

**Comment by nathanmarz** [comment]
Problem exists for `BEGINNING`, `END`, `FIRST`, `LAST`, `AFTER-ELEM`, `BEFORE-ELEM`.

Once fixed, should add tests for above on subvecs as well as `ALL` and `srange`.

**Comment by nathanmarz** [comment]
Fixed in master.
