### ISSUE TITLE
Transform FIRST

### ISSUE THREAD

**Issue by galdolber** [nathanmarz/specter#181]
I'm trying to transform only the first item in a collection, how can I do that?

```
(println
 (reduce
  (fn [all _]
    (transform [ALL (srange 1 2) (filterer #(> (:quantity %) 0)) FIRST] #(update-in % [:quantity] dec) all))
  {"1" {:quantity 1} "2" {:quantity 1} "3" {:quantity 1}
   "4" {:quantity 1} "5" {:quantity 1} "6" {:quantity 1}}
  (range 2)))

Returns ->> {1 {:quantity 0}, 2 {:quantity 0}, 3 {:quantity 0}, 4 {:quantity 0}, 5 {:quantity 0}, 6 {:quantity 0}}

What I need: ->> {1 {:quantity 0}, 2 {:quantity 0}, 3 {:quantity 1}, 4 {:quantity 1}, 5 {:quantity 1}, 6 {:quantity 1}}
```

**Comment by nathanmarz** [comment]
I don't understand what you're trying to do. Everything in your examples is unsorted maps, so what collection are you referring to?

**Comment by galdolber** [comment]
I'm trying to decrease the first positive quantity I can find, but only one on every iteration. 
In the example all the positive quantities are matching with the filterer.
The data structure looks like the one on the example:
{"1" {:quantity 1} "2" {:quantity 1} "3" {:quantity 1} "4" {:quantity 1} "5" {:quantity 1} "6" {:quantity 1}}

**Comment by nathanmarz** [comment]
The first positive quantity of what? The "quantity" maps are contained within an unsorted map where "first" isn't well-defined.

**Comment by galdolber** [comment]
The order doesn't matter, I should say, only one, not the first.

**Comment by nathanmarz** [comment]
Your example decrements :quantity for both "1" and "2", so still unclear.

**Comment by galdolber** [comment]
Yes, its just an example, I need to decrement only one positive quantity. After I do the filterer and FIRST, I end up with a collection of all positive quantities:

[{:quantity 1} {:quantity 1} {:quantity 1} {:quantity 1} {:quantity 1} {:quantity 1}]

I need to only affect one of them.

**Comment by nathanmarz** [comment]
Is this what you want?

```
(transform [FIRST :quantity] dec [{:quantity 1} {:quantity 1} {:quantity 1}])
;; =>  [{:quantity 0} {:quantity 1} {:quantity 1}]
```

**Comment by galdolber** [comment]
Yes but I'm missing the filterer there, I need it to only dec if it find a quantity > 0. In the last example it would do this:
```
(transform [FIRST :quantity] dec [{:quantity 0} {:quantity 0} {:quantity 1}])
;; =>  [{:quantity -1} {:quantity 0} {:quantity 1}]
```
When I need this:
```
(transform [??? FIRST :quantity] dec [{:quantity 0} {:quantity 0} {:quantity 1}])
;; =>  [{:quantity 0} {:quantity 0} {:quantity 0}]
```

**Comment by nathanmarz** [comment]
OK, I think you want this?

```
(transform [(subselect ALL :quantity pos?) FIRST]
  dec
  [{:quantity 0} {:quantity 0} {:quantity 2} {:quantity 1}])
;; => [{:quantity 0} {:quantity 0} {:quantity 1} {:quantity 1}]
```

**Comment by galdolber** [comment]
Perfect! thanks!
