### ISSUE TITLE
How to make transform work on defrecord:s ?

### ISSUE THREAD

**Issue by mattiasw2** [nathanmarz/specter#184]
I notice that there is some advanced defrecord support like #38, but when I try to use a simple transform, it just fails.

     (defrecord foo [a b])
     (sp/transform [sp/MAP-VALS] inc (->foo 1 2))

and I get 

     UnsupportedOperationException Can't create empty: sss4.migr_cdb.cdb_bench.foo  sss4.migr-cdb.cdb-bench.foo (form-init5181251144738676101.clj:81)

My goal is to as much as possible standardize on using transform.

**Comment by nathanmarz** [comment]
`MAP-VALS` is for maps, which a record is not. Records are "map-like" but don't implement the same interfaces as maps. I'll keep it open for now because I know `vals` works on records and I'm curious if there's more there that would support a non-fields-specific transformation like `MAP-VALS`.

**Comment by mattiasw2** [comment]
You are right, this is a unusual use-case that I do not even need. So, I was just distracted by error message.

I tested, and for my real use-cases, defrecord:s works as they should.
