### ISSUE TITLE
What's the difference between e.g. `select` and `select*`?

### ISSUE THREAD

**Issue by oskarkv** [nathanmarz/specter#186]
What's the difference between using the `select` macro and the `select*` function? They seem to be very similar in speed, and the code in them seems to be very similar as well. But the documentation only talks about the `select` macro. We all know that one should prefer functions over macros, and this leaves me confused.

**Comment by nathanmarz** [comment]
`select*` compiles the path on every invocation. If the path is already compiled, the performance cost will be minimal. If it is not, there will be a significant impact to performance, especially when part of the path is a sequence ([...]) or implicit nav (e.g. keyword). 

`select` analyzes the path to minimize the amount of runtime work to produce a compiled path for that invocation. I recommend reading https://github.com/nathanmarz/specter/wiki/Specter's-inline-caching-implementation to understand what this entails.
