### ISSUE TITLE
regards: collect-one 

### ISSUE THREAD

**Issue by JoePython1** [nathanmarz/specter#188]
I have a list of maps.

Currently I use the following pattern
```lisp
(select [ALL
            (collect-one :a)
            (collect-one :b)
            (collect-one :c)
           :d ]
           input)
```
Although the above solution works, It looks verbose. 
Is there a navigator which can collect all three keys (:a, :b :c) instead of three instances of collect-one's

**Comment by nathanmarz** [comment]
You can do:

```clojure
(select [ALL ((eachnav collect-one) :a :b :c) :d] input)
```

You can do `(def multi-collect-one (eachnav collect-one))` to make it reusable.
