### ISSUE TITLE
Fix problems with cljs tests on Travis

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#190]
The cljs build works fine locally, but something's causing it to consistently fail on Travis. It's possible there's some sort of timeout occurring, as the pull request adding the cljs build to Travis passed fine when it was built.

**Comment by darwin** [comment]
Try to install newer PhantomJS:
https://github.com/binaryage/cljs-devtools/blob/master/.travis.yml#L11-L15

**Comment by nathanmarz** [comment]
Unfortunately that didn't help. The first build ran fine, but trying a second time caused it to fail the same way.
