### ISSUE TITLE
Updating a nested value using setval

### ISSUE THREAD

**Issue by aphsa** [nathanmarz/specter#193]
I can successfully navigate to the nested empty value. 
```lisp
(s/select [s/ALL (s/collect-one :a) :b (s/walker empty?)]  y)
=> [["valofa" ""] ["valofa" ""] ["valofa" ""] ["valofa" ""]]
```

However I wanted update the nested empty value ("") with the collected val of :a.
I am unable to use setval for this.

**Comment by nathanmarz** [comment]
To use collected values you'll have to use `transform` and your own transform fn, like this:

```clojure
(transform [(collect-one :a) :b] (fn [a _] a) {:a 1})
;; => {:a 1 :b 1}
```
