### ISSUE TITLE
Writing a recursive map keys selector

### ISSUE THREAD

**Issue by lvh** [nathanmarz/specter#196]
I’ve been trying to write a specter recursive path to find all the keys in a nested data structure, but with no success. I managed to get here:

```
(def ^:private TREE-KEYS
  (sr/recursive-path
   [] p
   (sr/cond-path
    vector? [sr/ALL p]
    map? (sr/comp-paths [sr/MAP-KEYS] [sr/MAP-VALS p])
    sr/STAY sr/STAY)))

(sr/select TREE-KEYS {:a [{:b 1 :c 2}] :d {:e {:f 1}}})
```

The idea being that if it’s a vector, I want to recurse (that part seems to work), and if it’s a map then take the keys and then recurse into the vals.  The error I get is:

```
1. Caused by java.lang.IllegalArgumentException
   Not a navigator: #com.rpl.specter.impl.DynamicVal{:code p}
   com.rpl.specter.impl.DynamicVal
```

I can’t tell if this is a bug in recursive-path or if I’m just doing it wrong :)

**Comment by nathanmarz** [comment]
There's a lot wrong with your path, so I'll just show you the right way to do it:

```clojure
(def MY-NODES
  (recursive-path [] p
   (cond-path
    vector? (stay-then-continue ALL p)
    map? (stay-then-continue MAP-VALS p)
    )))

(select [MY-NODES map? MAP-KEYS] {:a [1 2 {:c 4 :d {:e 9}}] :b 10})
;; => [:a :b :c :d :e]
```

The right way to approach many recursive manipulations is to first define a path that navigates you to every node you care about, and then define the manipulation you want on top of that. In this case you're looking for all map keys, so you start by defining a path to all nodes in the data structure (vectors and maps). Then navigating to all the map keys is super simple.

You could also define `MY-NODES` to only navigate to maps, but this is more flexible/reusable.

**Comment by lvh** [comment]
Thanks a lot! The explanation especially helped to understand how to write it correctly :)
