### ISSUE TITLE
Keys cannot be strings

### ISSUE THREAD

**Issue by zmaril** [nathanmarz/specter#2]
`(select ["name"] {"name" 1}` 

Maybe I'm using this wrong or have the nesting wrong, but it seems like strings cannot be keys in maps.

**Comment by nathanmarz** [comment]
Use `keypath` to select a non-keyword key.

```clojure
(select [(keypath "name")] {"name 1})
```

**Comment by zmaril** [comment]
Oh! Thanks!

**Comment by hiram-madelaine** [comment]
This is very usefull, you should add it in the README :-)

**Comment by John-Madison** [comment]
I also vote for addition to README.

**Comment by nathanmarz** [comment]
OK, I added a `keypath` example to the README

**Comment by John-Madison** [comment]
Thanks, I really like using this library! I work with some nested maps that always use strings as keys for some reasons beyond my control. It would be really handy if the keypath function took multiple strings for a nested path.
