### ISSUE TITLE
Helper navs for common comparators

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#202]
During navigation, values are frequently filtered using a common comparison operator like `=`, `<`, `>`, etc. This is currently done by using an anonymous function inline with the path, such as #(= % 10). It may be useful to have helper navigator builders `=nav`, `<nav`, `>nav`, etc. so you can instead do something like:

```clojure
(setval [MAP-VALS (<nav 10)] NONE)
```

Not sure what the best names would be.

**Comment by nathanmarz** [comment]
Maybe `pred=`, `pred<`, `pred>` would be good names, as its consistent with `pred` navigator and the name provides info on what it does.

**Comment by nathanmarz** [comment]
Implemented in master

**Comment by aengelberg** [comment]
Why is this more useful than anonymous fns?

**Comment by nathanmarz** [comment]
I find it more readable. It's equivalent in both expressiveness and performance.
