### ISSUE TITLE
Support Number and String keypaths by default

### ISSUE THREAD

**Issue by michaelrkytch** [nathanmarz/specter#21]
Would you accept a pull request to extend StructurePath to java.lang.Number and java.lang.String by default?

It's quite common to use these as map keys, and I find wrapping them in (keypath) tends to clutter up code.

**Comment by nathanmarz** [comment]
I only did it for keywords since they can be used to navigate to values in regular Clojure code. I think I'll pass on this for now but may reconsider later. For the time being, if you want this functionality it's really easy to add the extensions in your own project.

**Comment by michaelrkytch** [comment]
I agree it's easy to extend the protocol to strings and numbers, but not sure I understand your comment about navigating to values.  This works in plain Clojure:

cljs.user=> (get-in {1 {"foo" :val}} [1 "foo"])
:val

**Comment by nathanmarz** [comment]
Oh I just meant that you can't do this in Clojure: ("a" {"a" 1}) or (1 {1 1}). On the other hand keywords have a built-in ability to navigate.
