### ISSUE TITLE
[cljs] Closure Warning - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript

### ISSUE THREAD

**Issue by darwin** [nathanmarz/specter#215]
Just compiled my code against bleeding edge [ClojureScript master](https://github.com/clojure/clojurescript/commit/9dc57c6c42e13eea405bc850cba53f583fd00916) and the generated code is newly producing a warning when passed through Google Closure Compiler:
https://gist.github.com/darwin/936829b27b73a91aa4dec0e9286671b8

It seems to have an issue with naked `.var` properties generated by emitting defrecord runtime code here (my theory): https://github.com/nathanmarz/specter/blob/cfb191e1cd4be66b09d8e4f671a4890372a32cef/src/clj/com/rpl/specter/impl.cljc#L425.

or maybe the code gets produced here?
https://github.com/nathanmarz/specter/blob/cfb191e1cd4be66b09d8e4f671a4890372a32cef/src/clj/com/rpl/specter/impl.cljc#L688-L698

Not a big issue. Just wanted to give a heads up.

**Comment by nathanmarz** [comment]
That's an unfortunate regression. Does this reproduce when running `(defrecord Foo [var])` at a cljs repl?

**Comment by darwin** [comment]
I believe this warning is present only in `:advanced` optimizations. Anyways I was able to reproduce it in ClojureScript test suite:
https://github.com/darwin/clojurescript/commit/9d2d366674e1d5ea6cf5d15764edcaff7004b881

**Comment by darwin** [comment]
FYI, here is today's discussion about this from #cljs-dev:
https://clojurians-log.clojureverse.org/cljs-dev/2017-06-26.html#inst-2017-06-26T17:04:54.337378Z

It is unlikely that this will get fixed by ClojureScript compiler. You will probably have to rename the `var` field, I think. 

Alternatively it should be also fixable by setting [`:language-in`](https://github.com/clojure/clojurescript/wiki/Compiler-Options#language-in-and-language-out) compiler option. But as a library author this is out of your control how people setup their compiler options.

**Comment by nathanmarz** [comment]
Thanks for all the info. Will fix by renaming that field.

**Comment by darwin** [comment]
I confirm. 

Compiled my code under :advanced mode:
1) ClojureScript 1.9.660 and Specter 1.0.2 => the warning was present.
2) ClojureScript 1.9.660 and Specter 1.0.3-SNAPSHOT => the warning was NOT present. 

I did a full clean of the project files to be sure.

**Comment by nathanmarz** [comment]
Great, thanks for all the help.
