### ISSUE TITLE
collect into maps?

### ISSUE THREAD

**Issue by ysmiraak** [nathanmarz/specter#221]
this library is awesome! i've just started to discover its convenience, but i wonder what's the best way to flatten embedded structure inside of a map:
```
{:a 0, :b [1 2]} => [{:a 0, :b 1} {:a 0, :b 2}]
```

i know i could do:
```
(->> {:a 0, :b [1 2]}
     (select [(collect-one :a) :b ALL])
     (transform ALL (partial zipmap [:a :b])))
```

but this produce intermediate result: `[[0 1] [0 2]]`; and with larger maps, i would have to write multiple `collect-one`.

then i tried this:
```
(->> {:a 0, :b [1 2]}
     (transform [(collect-one (submap [:a])) :b ALL] #(assoc %1 :c %2))
     :b)
```

but this produce intermediate result: `{:a 0, :b [{:a 0, :c 1} {:a 0, :c 2}]}`, which looks hacky.

what's the best way to achieve this goal with specter?

**Comment by nathanmarz** [comment]
This is a full transformation, so you're best off just using `reduce` for this. Specter is appropriate when you're changing part of a data structure and keeping the rest of it the same.
