### ISSUE TITLE
Make new code path for select-first

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#23]
Using selectors like ALL is inefficient when doing a select-first, since it will continue traversing beyond the first element found. For ALL, a lazy version would help with this but then adds the overhead of lazy sequences – and you would still have the overhead of wrapping the result in a sequence. Having a special code path for select-first would allow this use case to be handled more efficiently.

This issue would also make selected? much more efficient.

This should be done as a new protocol, with a default implementation over select\* provided if the protocol impl is missing.

**Comment by nathanmarz** [comment]
#111 somewhat reduces the utility of this issue

**Comment by aengelberg** [comment]
Not certain why that last comment is true, because AFAIK #111 doesn't provide any laziness which speeds up the "first" case.

**Comment by nathanmarz** [comment]
#111 via `select-any` already speeds up all navigators that traverse at most one value, e.g. `keypath`, `FIRST`, `LAST`, etc.  Those were all cases that this feature would have addressed.

With the existence of `select-any`, a specialized `select-first` will only address navigators that traverse more than one element. So this feature would still be useful, just not as much as before.

**Comment by nathanmarz** [comment]
This feature idea might be completely subsumed by an alternate feature of "early termination" (discussed in #121). By using `reduced` to indicate traversal should be finished, and `reduced?` in `ALL` to detect termination, the desire to avoid unnecessary traversal can be satisfied. And the `reduced`/`reduced?` approach would be superior because it's not limited to early termination after a single element, but can do it under whatever conditions are needed (e.g. 2 elements, when the elements match some predicate, etc.). 

With such a feature, the continuation function for `select-first` would just be `reduced`. That should trigger  an immediate return and all traversal to stop.

Early termination would function differently for `select` vs. `transform`. For `select` it would stop traversal and do an immediate return. For `transform` it would stop calling `next-fn` on further values and just leave those unchanged. 

An open question is how to deal with a path like `[ALL ALL]` where you want to early terminate the second `ALL` but not the first. One idea is to use `freshpath` from #121 brainstorm to indicate these boundaries. So `[ALL (freshpath ALL)]` would early terminate the second `ALL` but not the first. This calls into question whether this creates complexity with stateful navigator resets. Perhaps you want stateful resets but also early termination to go through, which this design would not support. This requires further investigation.

**Comment by nathanmarz** [comment]
Another note:

Something like `(transform [ALL :a (takenav 3)] ...)` would return a reduced value into the navigator for :a. So the navigator for keywords would have to check if transformed value is `reduced?: if so, deref it, do the normal assoc, and then wrap the normal return value in `reduced`. Similarly for `ALL`, if one of its subvalues is `reduced?`, then it should wrap its return value in `reduced`. 

Whether the constant checking/wrapping/unwrapping causes performance problems remains to be seen. Also, this feature implies every single navigator would have to be aware of and handle `reduced`, so whether this can be abstracted away to any extent should be investigated.

**Comment by nathanmarz** [comment]
The addition of early termination from #125 has made `select-first` avoid unnecessary traversal and removes the need for a special code path.
