### ISSUE TITLE
Consider additional implicit navigators

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#232]
1. string -> keypath
2. number -> nthpath
3. regex -> regex-nav

**Comment by mwfogleman** [comment]
I made a branch for this here:
https://github.com/mwfogleman/specter/tree/implicit

Happy to rebase and make a PR if and when you decide you want this.

**Comment by nathanmarz** [comment]
Having numbers implicitly convert to `nthpath` may be confusing to users if using a map with number keys. It may be more intuitive for numbers to convert to `keypath` as well. With this design, numbers on their own will work for maps and vectors but not lists.

**Comment by nathanmarz** [comment]
Other types to consider for implicit navs:

1. Character
2. Boolean
3. Symbol

Seems like it would make sense for all of these to convert to `keypath`.

**Comment by nathanmarz** [comment]
Implemented in master for all above types with numbers converting to `keypath`
