### ISSUE TITLE
Add dates to Changelog

### ISSUE THREAD

**Issue by DjebbZ** [nathanmarz/specter#243]
Hello,

It would be great if the CHANGES.md file displayed the date of release along with the versions.

Because I'm a nice guy lol, here's what I found in `git` to help finding the dates :

`git tag --list --format="%(refname:short) %(creatordate:short)"`

_NOTE_: you may want to swap `creatordate` for one of `authordate`, `committerdate`, `taggerdate` to get some result. I tried them all, some don't always give a result. YMMV. I'm not git expert.

**Comment by nha** [comment]
https://github.com/nathanmarz/specter/releases has dates?

**Comment by DjebbZ** [comment]
Indeed! 😅

Will try a PR in the next few days.


Le 6 févr. 2018 18:46, "Nicolas Ha" <notifications@github.com> a écrit :

https://github.com/nathanmarz/specter/releases has dates?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nathanmarz/specter/issues/243#issuecomment-363505745>,
or mute the thread
