### ISSUE TITLE
`multi-path` thoughts

### ISSUE THREAD

**Issue by esseswann** [nathanmarz/specter#248]
Is there a better way for creating dynamic multi-path selections, instead of using `apply`:
```clojure
(defn foo [data keys]
  (select (apply mutli-path keys) data)
```

Why couldn't we make `select` accept any number of arguments to get rid of `multi-path` at all:
```clojure
(select path path path ... data)
```
I can help with implementation of the latter

**Comment by nathanmarz** [comment]
If you're trying to access a subset of keys in a map, you can either do it that way or with `(select [(submap keys) ...] ...)`

Using `multi-path` at the top-level is far from common, so there's no point in complicating the API like that. `(select (multi-path ...` is not burdensome at all.
