### ISSUE TITLE
add INFO macro for easy exploration of complex data structures

### ISSUE THREAD

**Issue by behrica** [nathanmarz/specter#250]
I use specter to first "explore" complex data structures, before using specter to select relevant pieces.
I found it very useful in this context to create my own INFO macro,
which returns, depending on the current structure different information:

- names of keys, if map
- length of sequence, if sequential
- a "shortened string", if string

Having this INFO macros at the end of the specter path guaranties as well that the returned data from select will not be too long to crash emacs /cider, if printed by accident.

It allows a very iterative way of exploring a data structure by adding :+1: keyword or "FIRST" to the path just before the INFO in order to easily dig into complex structures.

The code for this INFO macro itself is very short.

Maybe something like this could be added to specter.

```
(defn shorten-string [s]
  (if (> (count s) 1000)
    (str (.substring s 0 1000) " ...")
    s)
  )

(defn info [x]
  (cond (string? x)   (shorten-string x)
        (map? x) (str "keys: "(keys x)) 
        (sequential? x) (str "count: " (count x))
        true x))
  
  
(defnav INFO []
    (select* [this structure next-fn]
             (next-fn (info structure)))
  (transform* [this structure next-fn]
              nil))

```

**Comment by nathanmarz** [comment]
Exploring/visualization of data structures is an interesting problem space that I think is best done as its own project
