### ISSUE TITLE
`if-path` doesn't allow simple keywords as functions

### ISSUE THREAD

**Issue by DjebbZ** [nathanmarz/specter#252]
Hi,

I've noticed something that could potentially be better: when defining a `recursive-path` and using `if-path` in it, `if-path` doesn't use the keyword I pass as a predicate. 

Example :

``` clojure
;; example data-structure
(def TREE
  [{:id 1 :children [{:id 11 :leaf true}
                     {:id 12 :children [{:id 121 :leaf true}]}]}
   {:id 2 :children [{:id 21 :children []}]}])

;; recursive navigator
(def LEAVES
  (sp/recursive-path [] p [sp/ALL (sp/if-path :leaf) ;; :leaf, not #(:leaf %)
                                              sp/STAY
                                              [:children p])]))

;; query the leaves
(sp/select LEAVES TREE)

;; expected 
; => [{:id 11, :leaf true} {:id 121, :leaf true}]
;; actual
; => [{:id 1, :children [{:id 11, :leaf true} {:id 12, :children [{:id 121, :leaf true}]}]}
 {:id 2, :children [{:id 21, :children []}]}] ;; the complete data-structure
```

I get the expected result if I use the function form `#(:leaf %)`.

After a quick investigation, I noticed that `com.rpl.specter.navs/extract-basic-filter-fn` (used by `if-path`) tests the path with `fn?`, not `ifn?`. Using `ifn?` would make it work with all data-structures that can work as functions, like keywords, sets, maps etc.

Am I right ? Is it worth changing ? I would say yes but I'm not sure of all the implications.

**Comment by nathanmarz** [comment]
`if-path` considers the condition "true" if it navigates to at least one value. A keyword always navigates. If you want the condition to be true only if the key exists, then use `(must :some-key)`. If you want it to be true only if the value for the key is truthy, then do `[:some-key identity]`.

**Comment by DjebbZ** [comment]
Thank you. In my precise case `must` is what I need.
