### ISSUE TITLE
performance on transform big atom

### ISSUE THREAD

**Issue by jiacai2050** [nathanmarz/specter#257]
I create a benchmark at: https://gist.github.com/jiacai2050/082a05394ac4ad8f59953d95519740d5

It seems that specter is 2 times slower than vanilla clojure. I also try [this](https://github.com/nathanmarz/specter/blob/master/scripts/benchmarks.clj), which show specter is faster. 

Is there anything I'm missing? AFAIK, use one big atom to hold app states is preferred in many clojure apps, eg: [re-agent](https://github.com/reagent-project/reagent).

**Comment by nathanmarz** [comment]
You're Specter code can be improved significantly by replacing `subset` usage with `NONE-ELEM`, which is much faster for inserting a single element.

```
(setval [ATOM app-id peer-id NONE-ELEM]
            channel-id
            clients)))
```

**Comment by nathanmarz** [comment]
You should also wrap `app-id` and `peer-id` in `keypath` so Specter statically knows what those are. This will be a big performance boost.

```
(setval [ATOM (keypath app-id peer-id) NONE-ELEM]
            channel-id
            clients)))
```

**Comment by jiacai2050** [comment]
Thanks,  Specter is pretty faster after modification.

Using `NONE-ELEM`  for inserting sounds reasonable, why `keypath` also improve performance?

**Comment by nathanmarz** [comment]
By wrapping in `keypath`, Specter statically knows what navigator is at those points and the inline compiler can encode that information for all future runs of that callsite. This wiki page goes into detail on that: https://github.com/nathanmarz/specter/wiki/Specter's-inline-caching-implementation
