### ISSUE TITLE
performance of must

### ISSUE THREAD

**Issue by jiacai2050** [nathanmarz/specter#258]
```clj

(quick-bench 
 (let [m {:a "some-val"}]
   (if (contains? m :a)
     (assoc m :a "$")
     m))
 )

(quick-bench 
 (let [m {:a "some-val"}]
   (setval [(must :a)]
           "$"
           m))
 )

```

```
;; clojure
Evaluation count : 19747476 in 6 samples of 3291246 calls.
             Execution time mean : 28.269609 ns
    Execution time std-deviation : 0.386183 ns
   Execution time lower quantile : 27.600519 ns ( 2.5%)
   Execution time upper quantile : 28.637442 ns (97.5%)
                   Overhead used : 1.743376 ns

;; specter
Evaluation count : 4257258 in 6 samples of 709543 calls.
             Execution time mean : 134.752354 ns
    Execution time std-deviation : 11.815950 ns
   Execution time lower quantile : 118.779726 ns ( 2.5%)
   Execution time upper quantile : 147.331239 ns (97.5%)
                   Overhead used : 1.743376 ns
```
As benchmark above show, Specter is much slower than pure Clojure.

For me, Specter is faster than pure Clojure in most situation, but I wonder what's Specter not good at?

**Comment by nathanmarz** [comment]
The Clojure code you wrote is identical to what the `must` navigator does. Executing a path via Specter adds some overhead, namely a couple more layers of function calls to get to the transformation logic. It's these situations of a single simple navigator like `must` or `keypath` that Specter will benchmark as slower. As soon as you compose multiple navigators together, or use a more involved navigator like `ALL` or `MAP-VALS`, Specter will crush the performance of reasonable vanilla Clojure.
