### ISSUE TITLE
comparison with a graph-db

### ISSUE THREAD

**Issue by drorbemet** [nathanmarz/specter#263]
What are the advantages / disadvantage of Specter over a graph-database like neo4j?

With Specter I get access down to the level of simple values. 
Whereas interacting with a graph-db I can select only down to the level of nodes/edges with their properties and possible loose writing access.

I did some data analysis using specter on a domain specific data structure in clojure.
Now how I ask myself in which cases I could use a graph-db right from the start?

What are your experiences?

Thanks for some hints on how to decide when to use specter and when to consider a graph-db like neo4j.

**Comment by nathanmarz** [comment]
These aren't really comparable. Specter lets you efficiently and concisely manipulate regular program data structures, and Neo4j is a database with a particular indexing/query model.
