### ISSUE TITLE
Way to print out a path

### ISSUE THREAD

**Issue by barrtrek** [nathanmarz/specter#266]
Is there a function or a process for taking a path object and printing out a full human-readable representation?
We build some of our paths dynamically and they sometimes contain other paths.  It would be a great debugging tool to see the ultimate path that was constructed.

**Comment by nathanmarz** [comment]
This isn't possible now, but there's a long term goal to make paths data that can be inspected (while still executing just as efficiently). This will require a major restructuring of the project so probably won't happen for awhile.

**Comment by barrtrek** [comment]
Hey, thanks for the response Nathan.  Think we'll be using Specter for the long haul in some pretty hard hit code, so I'm glad its somewhere on your roadmap!
