### ISSUE TITLE
Nested map navigation with values

### ISSUE THREAD

**Issue by barrtrek** [nathanmarz/specter#268]
I'm looking for a solution for a navigator that will let me navigate by key-val pairs or something equivalent.  Example:

```
{:cookie-basket [{:cookie-type "chocolate"
           :cookie-properties {:property-name "chip-count"
                               :property-value 100}}
          {:cookie-type "peanut-butter"
           :cookie-properties {:property-name "density"
                               :property-value "high"}}
          {:cookie-type "red-velvet"
           :cookie-properties {:property-name "chip-count"
                               :property-value 80}}]}

```

How would I get to the property 100 using navigators? 

I'm able to get to the value using something like 
```
[:cookie-basket ALL #(= (:cookie-type %) "chocolate") 
  :cookie-properties ALL #(= (:cookie-property %) "chip-count") 
  :property-value]
```
but the filters take out nils which I was hoping to use.

I was looking at 'selected?' but couldn't figure out how to navigate based on values.

Thanks!

**Comment by barrtrek** [comment]
Think I lost the vectors of properties in the example. 

Regardless, this is similar to the solution I've been using.  If there were a navigator, though, that could accomplish this rather than a filter, I'd be able to keep the nils that would be generated by the missed navigators.  
Like if I used this 
(select [:cookie-basket ALL #(= (:cookie-type %) "peanut-butter")] data), 
I'd get 
[{:cookie-type "peanut-butter"
           :cookie-properties {:property-name "density"
                               :property-value "high"}}]

But if there were a navigator something like 
[:cookie-basket ALL {:cookie-type "peanut-butter"}] 
or maybe 
[:cookie-basket ALL (selected? :cookie-type "peanut-butter")]
where the selection would go all the way down to the value,

I believe I'd get 
[nil {:cookie-type "peanut-butter"
           :cookie-properties {:property-name "density"
                               :property-value "high"}} nil]

If there's nothing like this, I'll try and work around it, I just wondered if there were some selectors I didn't know about.

Thanks!

**Comment by nathanmarz** [comment]
You can do something like this to navigate to nil when there isn't a match: `[:cookie-basket ALL (if-path #(= "peanut-butter" (:cookie-type %))` <some subpath> (view (fn [_] nil))]`

Also, it's easy to make higher level paths using `defn` and `path` to combine many navigators together.

**Comment by barrtrek** [comment]
Yes!
Had to tweak a little bit for future reference:
`[:cookie-basket ALL (if-path #(= (:cookie-type %) "peanut-butter") STAY (view (fn [_] nil)))]`

Needed the 'then-path' in there along with the else path.  

I should be able to use this I think!  I'll probably extract some of the syntax into path functions for clarity as you suggested.

I truly, truly appreciate the support.

Thanks!
