### ISSUE TITLE
Graph Navigators and Documentation

### ISSUE THREAD

**Issue by Folcon** [nathanmarz/specter#269]
Hi,
I've looked at #241, and I was banging my head against this for hours.

I've been using loom to try and create a navigator that walks the graph (and hopefully n neighbours), and I only just managed to get it to give me a topological sort.

I was working with this:
```clojure
(def g
  {:edges
   [{:strength 0.7, :src "dog", :dst "mammal"}
    {:strength 0.7, :src "cat", :dst "mammal"}
    {:strength 0.7, :src "fox", :dst "mammal"}
    {:strength 0.7, :src "elk", :dst "mammal"}
    {:strength 0.7, :src "ant", :dst "insect"}
    {:strength 0.7, :src "bee", :dst "insect"}
    {:strength 0.7, :src "carp", :dst "fish"}
    {:strength 0.7, :src "pike", :dst "fish"}
    {:strength 0.1, :src "elk", :dst "cat"}
    {:strength 0.1, :src "ant", :dst "carp"}
    {:strength 0.1, :src "bee", :dst "elk"}
    {:strength 0.1, :src "cat", :dst "dog"}
    {:strength 0.1, :src "ant", :dst "fox"}
    {:strength 0.1, :src "cat", :dst "pike"}],
   :nodes
   [{:id "mammal", :group 0, :label "Mammals", :level 1}
    {:id "dog", :group 0, :label "Dogs", :level 2}
    {:id "cat", :group 0, :label "Cats", :level 2}
    {:id "fox", :group 0, :label "Foxes", :level 2}
    {:id "elk", :group 0, :label "Elk", :level 2}
    {:id "insect", :group 1, :label "Insects", :level 1}
    {:id "ant", :group 1, :label "Ants", :level 2}
    {:id "bee", :group 1, :label "Bees", :level 2}
    {:id "fish", :group 2, :label "Fish", :level 1}
    {:id "carp", :group 2, :label "Carp", :level 2}
    {:id "pike", :group 2, :label "Pikes", :level 2}]})

(defn make-graph [{:keys [nodes edges] :as graph}]
  (let [node-map (into {} (map (fn [node] [(:id node) node])) nodes)
        edge-vec (into [] (map (fn [edge] [(get node-map (:src edge)) (get node-map (:dst edge)) edge])) edges)]
    (apply loom/weighted-digraph edge-vec)))
```
Which gives me a simple loom graph. Calling `loom.alg/topsort` gives me:
```clojure
({:id "bee", :group 1, :label "Bees", :level 2}
 {:id "elk", :group 0, :label "Elk", :level 2}
 {:id "cat", :group 0, :label "Cats", :level 2}
 {:id "pike", :group 2, :label "Pikes", :level 2}
 {:id "ant", :group 1, :label "Ants", :level 2}
 {:id "carp", :group 2, :label "Carp", :level 2}
 {:id "fish", :group 2, :label "Fish", :level 1}
 {:id "insect", :group 1, :label "Insects", :level 1}
 {:id "dog", :group 0, :label "Dogs", :level 2}
 {:id "fox", :group 0, :label "Foxes", :level 2}
 {:id "mammal", :group 0, :label "Mammals", :level 1})
```

I finally worked out that I could write the `loom.alg/topsort` navigator as follows:
```clojure
(s/defnav
  ^{:doc "Performs Topological Sort"}
  TOPSORT
  []
  (select* [this structure next-fn]
    (next-fn (la/topsort structure)))
  (transform* [this structure next-fn]
    (next-fn (la/topsort structure))))
```

It might be nice to just mention an example about how to create a navigator somewhere? Reading the source to work this out is helpful, but it's pretty easy to get lost as this is a pretty complex lib at this point. (Not that I mind that too much, it's powerful :) )

**Comment by nathanmarz** [comment]
I agree the wiki could use a good page about defining custom navigators. It's worth adding that to #56 

That `TOPSORT` navigator you defined is the same as `(view la/topsort)` and definitely not what you want. My `TOPSORT` works like `ALL` except on a graph (specifically DAG). So the `select*` codepath calls `next-fn` on every node, and the `transform` codepath is a reduce to produce the updated graph.

**Comment by Folcon** [comment]
Ok, so more like this?
```clojure
(require '[com.rpl.specter.navs :as sn])

(s/defnav
  ^{:doc "Performs Topological Sort"}
  TOPSORT []
  (select* [this structure next-fn]
    (sn/all-select (la/topsort structure) next-fn))
  (transform* [this structure next-fn]
    (sn/all-transform (la/topsort structure) next-fn)))
```

**Comment by nathanmarz** [comment]
No... `transform*` for `TOPSORT` should return a graph, for one.

More specifically, the way my `TOPSORT` works is to navigate to "pointers" to nodes. A "pointer" is a vector of `[graph, node-id]`. From a pointer to a node I can navigate to all children/parents with the `CHILDREN`/`PARENTS` navigators. I have a `NODE` navigator that navigates from a pointer to the value for the node.

My `transform*` roughly looks like this:

```clj
(reduce (fn [graph node-id]
            (-> [graph node-id] next-fn (nth 0)))
          graph
          (loom/topsort graph)))
```

**Comment by Folcon** [comment]
Ok, I'm going to spend some time looking at how `map-key` and `indexed-vals` are implemented, from what I understand about what you're saying working with maps and then navigating to the keys/vals should be somewhat analogous.

Sorry, I don't have much experience using specter, (as you should be able to tell) much of my usage has been minor variations on examples. I've not really had to use it in anger until now.

Thanks for your help.

**Comment by nathanmarz** [comment]
A better one to look at for learning rather than `indexed-vals` is `ALL`. It's more code but that's only because it specializes per collection type. The semantics of `ALL` are much simpler than `indexed-vals`. 

If you have any more questions, feel free to open more issues or ask in the #specter channel on Clojurians.

**Comment by Folcon** [comment]
Hi @nathanmarz, I've looking at this some more and I've managed to get `TOPSORT` working the way you mentioned as and I'm now working out `NODE`. However I now have a more philosophical question I suppose?

I've worked out three different versions of `TOPSORT`, which have different implications for how `NODE` should work.

1) `TOPSORT` returns nodes on `select`, `NODE` doesn't really have a purpose here.
```clojure
(s/defnav
  ^{:doc "Performs Topological Sort, where the selector returns the nodes"}
  TOPSORT []
  (select* [this structure next-fn]
    (sn/all-select (map (partial attr/attrs structure)
                        (la/topsort structure)) next-fn))
  (transform* [this structure next-fn]
    (reduce (fn [graph node-id]
              (-> [graph node-id] next-fn (nth 0)))
            structure
            (la/topsort structure))))
```

2) `TOPSORT` returns node-ids on `select`, I'd need to use `collect`, but I should be able to use `NODE` to get the nodes.
```clojure
(s/defnav
    ^{:doc "Performs Topological Sort"}
    TOPSORT []
    (select* [this structure next-fn]
      (sn/all-select (la/topsort structure) next-fn))
    (transform* [this structure next-fn]
      (reduce (fn [graph node-id]
                (-> [graph node-id] next-fn (nth 0)))
              structure
              (la/topsort structure))))
```
3) `TOPSORT` returns a vector of [graph node-id] 's on `select`, the same as transform. (I sort of took you literally with `select` being like `ALL`).
```clojure
(s/defnav
  ^{:doc "Performs Topological Sort"}
  TOPSORT []
  (select* [this structure next-fn]
    (su/doseqres s/NONE [node-id (la/topsort structure)]
       (next-fn [structure node-id])))
  (transform* [this structure next-fn]
              (reduce (fn [graph node-id]
                        (-> [graph node-id] next-fn (nth 0)))
                      structure
                      (la/topsort structure))))
```

I'm just wondering, which better fits the way specter works? Or is that more a decision on the developer side?

I'm currently leaning on the side of option `3)`, as I can then represent `NODE` as:
```clojure
(defn add-attrs-to-node-or-edge [g [node-or-edge-id attr-map]]
  "Because for some reason loom doesn't have this"
  (reduce (fn [inner-g [k v]]
            (attr/add-attr inner-g node-or-edge-id k v))
          g attr-map))

(s/defnav
  ^{:doc "Gets the node"}
  NODE []
  (select* [this structure next-fn]
    (next-fn (apply attr/attrs structure)))
  (transform* [this structure next-fn]
    (let [[graph node-id] structure]
      [(add-attrs-to-node-or-edge graph [node-id (next-fn (attr/attrs graph node-id))])
       node-id])))
```
Sorry if it's a bit nonsensical, I just coded this up and wanted to check my understanding :)...

**Comment by nathanmarz** [comment]
You 100% want to go with option 3. Besides the cognitive benefits of navigators acting the same in selects and transforms, it's also essential for the navigator to work with `subselect`.

Yes, I'd very much like someone to build an open source graph navigation library and would be happy to help guide that work.

**Comment by Folcon** [comment]
Ok, well how would you want to do it?

One of the things I'm presently working on is a general library for manipulating grammars of different kinds. Once I moved away from just working with strings to also supporting data structures I got really interested in `specter`. It's been languishing recently, but I've started working on it again when I discovered that graph grammars exist and seeing as I'm working a fair bit with graphs at the moment I decided to extend it to work with graphs.

I could:
1) Treat graph navigation as part of the core of the lib I'm building
2) Treat graph navigation as it's own lib, that's heavily used by my own lib.

Is any of this of interest?
