### ISSUE TITLE
Clean up the DSL

### ISSUE THREAD

**Issue by expez** [nathanmarz/specter#27]
You might be blind to this, as you've been using specter for so long, but I found the specter DSL somewhat aesthetically lacking.  Here are my major gripes, in no particular order:

* Mixing of lower-case and upper-case selectors.
* Duplicating existing names, e.g. `srange` for `range` and `filterer` for `filter`.

It seems to me that both of these could be easily fixed by just turning functions like `transform` and `select` into macros and then having that macro call a transformer on the navigation spec, which would transform `first` to `FIRST`, `range` to `srange` etc before delegating to the existing implementation.

**Comment by nathanmarz** [comment]
The upper case selectors like ALL and FIRST are done like that so they're clearly delineated from regular functions (which act as filters). I'm also strongly against any of the macro-magic that you suggest, as I think that's just confusing. It also forces Specter to have a bunch of special cases just to "normalize" names, whereas now Specter is just a couple protocols and completely agnostic to anything built on top of that.

**Comment by expez** [comment]
I think this is somewhat important, and it would probably be impossible to change after `1.0.0`, so at the risk of wasting both our times, if you've already made up your mind:

> The upper case selectors like ALL and FIRST are done like that so they're clearly delineated from regular functions (which act as filters).

`ALL` and `FIRST` et.al. are also filters.  `ALL` is a filter letting anything pass through, and `FIRST` is a filter letting only the first element through.

>  I'm also strongly against any of the macro-magic that you suggest, as I think that's just confusing.

Why do you think this would be confusing?  Using macros would not change the experience of using specter at all, from the end-user perspective.  The only thing I can think of is that `select` or `transform` couldn't be used as higher order functions (without wrapping them in `#()`, but I don't think that's a very common pattern anyway.

> It also forces Specter to have a bunch of special cases just to "normalize" names,

This would just be a lookup map `{clojure.core/first FIRST, clojure.core/last LAST}` containing only the names of `core` you'd be shadowing in the DSL, which off the top of my head are only `first`, `last`, `filter` and range.

> now Specter is just a couple protocols and completely agnostic to anything built on top of that.

This wouldn't change by adding a thin veneer to afford a more (imo) pleasant DSL.

**Comment by nathanmarz** [comment]
"filter" in the context of how a function is interpreted means look at an element and decide whether or not to stay navigated at that element depending on whether the function returns true or false. This is completely different than what ALL, FIRST, and LAST do.

Regarding the lookup map, right now the semantics are very clear: every Clojure function is interpreted as a filter. Adding the lookup map would change the semantics to: every Clojure function is interpreted as a filter, except for first, last, filter, range, etc. which are interpreted completely differently. I find that very confusing.

Whether something is "pleasant" is in the eye of the beholder, and I find the current Specter API very pleasant – it's clear, straightforward, concise, fast, and powerful.
