### ISSUE TITLE
Nested Data Structures created with collections

### ISSUE THREAD

**Issue by barrtrek** [nathanmarz/specter#270]
I love that Clojure lets me create data structure paths that don't exist previously.  Specifically nested key-map structures.  But I keep coming across the need to create collections along the way and possibly continue with nested maps.
For example, this works great:
```
(setval [:a :b] "JIM" {})
-> {:a {:b "JIM"}}
```

But if :b should have a collection, I can do this in some cases, but there's less control:
```
(setval [:a AFTER-ELEM] {:b "JIM"} {})
-> {a ({:b "JIM"})}
```
In that case, it would be great if I could force the collection to be a vector, but I'm not sure how I'd do that.

Ideally, this would work
```
(setval [:a AFTER-ELEM :b] "JIM" {})
-> {:a [{:b "JIM"}]}
```
But alas, it appears we can't use selectors after the BEFORE/AFTER-ELEMs.

Have I missed some functionality or is there a new selector that could solve one or both of these problems?

Thanks!

**Comment by nathanmarz** [comment]
You can use `nil->val` to force the collection type. There are prebuilts `NIL->VECTOR`, `NIL->LIST`, and `NIL->SET`. For example: `(setval [:a NIL->VECTOR AFTER-ELEM] :b {})` -> `{:a [:b]}`

**Comment by nathanmarz** [comment]
I don't know what you mean by "key navigation post collection creation"

**Comment by barrtrek** [comment]
Sorry, and perhaps this is just 'post AFTER/BEFORE-ELEM' regardless if it creates an empty collection or not.
```
(setval [:a NIL->VECTOR AFTER-ELEM :b] "JIM" {})
-> {:a [{:b "JIM"}]}
```
Is there a reason this kind of navigation won't work?  Trolled through the code a bit and couldn't figure out why it was giving me ClassCastException Clojure.lang.Keyword cannot be cast to a Clojure.lang.Associative.  Its like AFTER-ELEM isn't sending the element to the next navigator in a way that a key would normally be able to create a new map with that key in it.

**Comment by nathanmarz** [comment]
`AFTER-ELEM` navigates to `NONE` which is a keyword. Think of it as navigating to "void". `AFTER-ELEM` and like navigators only make sense to use at the terminal point of a path in conjunction with `setval`

**Comment by barrtrek** [comment]
Ah, so it behaves different than, say LAST because I could keep navigating after that.  Unfortunately since NIL->VECTOR creates an empty array, there's no way for me to get into any elements of that to add anything and keep navigating.
Tried some variations of:
`[:a NIL->VECTOR LAST (nil->val {}) :b]`
Again, won't work because the vector is empty.  So I don't see any functionality for adding an empty map to a created vector and then continue navigating.  Perhaps I'll mess around with adding a version of AFTER-ELEM that doesn't terminate.

Perhaps there are some vagaries I don't understand, but I think it still makes sense to allow navigation post-AFTER-ELEM (for setval purposes).
```
(setval [:a NIL-VECTOR AFTER-ELEM :b] "hey" {})
-> {:a [{:b "hey"}]}
```
It would allow you to add maps with a key to a list just as you can when you are doing
```
(setval [:a :b] "hey" {})
->{:a {:b "hey}}
```
Thanks for the responses and the insight!

**Comment by nathanmarz** [comment]
You can do this:

```clj
(defn force-val [v] (view (fn [_] v)))
```

Then you can do `[:a NIL->VECTOR AFTER-ELEM (force-val {}) :b]`

**Comment by barrtrek** [comment]
Exactly what I need!  Probably will make a path to incorporate NIL->VECTOR AFTER-ELEM (force-val {}).  
Incredible support sir!
