### ISSUE TITLE
setval using a path that applies regex-nav multiple times in succession

### ISSUE THREAD

**Issue by drorbemet** [nathanmarz/specter#278]
There are situations in which I would like to split a regexp in multiple steps.
My goal is to select and edit a substring in a text using multiple applications of regex-nav in succession. 

But I am having difficulties to find a way to select a regexp-match-group and then apply regex-nav a second time.

What are the options to prepare a regex-match for a second application of regex-nav within a specter-path?
Is it necessary to develop a variation of regex-nav using select-one* and setval for this?

Here is a test setup to find a solution:

``` clojure
(def structure "Mary: the 1st George: the 2nd Arthur: the 3rd")
(def path-to-2nd
  ;; "a path on the substring: 2nd"
  [
  ;; a first application of regex-nav to narrow in on a substring
  (regex-nav #"(\S+):\ (\w+ [\d\w]+)")

   ;; selecting a regex-match-group
   ;; select the second group
   (subselect (nthpath 2))
   (nthpath 0)

   ;; select the substring to edit
   ;; by applying a second regex-nav to the selected regex-math-group
   (regex-nav #"\w+ (2nd$)")
   (nthpath 1) ])

;; testing path-to-2nd:
(select-one path-to-2nd structure )
;; =>  2nd
;; it returns the substring 2nd => so the path seems to work

;; edit the substring 2nd in structure - replacing or transforming
(setval path-to-2nd "20nd" structure)
;; => Exception: clojure.lang.PersistentVector cannot be cast to java.lang.String
```

What am I missing?
Thanks for any hints on this one.

**Comment by nathanmarz** [comment]
I don't think you need to use regex groups. You probably just want to do `(subselect #"...")` to navigate to all the matches as a sequence, and then you can choose which match you'd like to edit using `nthpath`:

```
user=> (setval [(subselect #"\S+:\ \w+ [\d\w]+") (nthpath 1)  #"\d+\w+$"] "20th" structure)
"Mary: the 1st George: the 20th Arthur: the 3rd"
```

**Comment by drorbemet** [comment]
Ah, ok. That regular rexpressions are supported as paths directly via specters implicit-nav totally escaped my notice. I didn't even find a hint now in the docs after knowing it. But I found  com.rpl.specter extend-type ImplicitNav now.

Here is an example for a solution to navigate and edit pairs of tags using regex in succession without grouping.

``` clojure
(def structure "text lbla unknown lblb the unknown value  lbeb unknown-after lbea text")
 (select [#"lbla.*lbea" #"lblb.*lbeb" #"(?<=lblb ).*?(?= *lbeb)"] structure)
 (setval [#"lbla.*lbea" #"lblb.*lbeb" #"(?<=lblb ).*?(?= *lbeb)"] "the new value" structure)
```
