### ISSUE TITLE
Find all instances of key in map in wiki exception if key doesn't exist

### ISSUE THREAD

**Issue by tanzoniteblack** [nathanmarz/specter#279]
https://github.com/nathanmarz/specter/wiki/Using-Specter-Recursively#navigate-to-all-of-the-instances-of-one-key-in-a-map This example has a bug, if you call the examples with a key that doesn't exist (like `:asdf`), then an exception is thrown: 

```Execution error (IllegalArgumentException) at com.rpl.specter.navs/all-select (navs.cljc:26).
Don't know how to create ISeq from: java.lang.Long
```

To fix this, `(def map-key-walker (recursive-path [akey] p [ALL (if-path [FIRST #(= % akey)] LAST [LAST p])]))` should have a `coll?`, or something similar to make sure it's the value is a collection, at the start of the `if-path`:

`(def map-key-walker (recursive-path [akey] p [ALL (if-path [coll? FIRST #(= % akey)] LAST [LAST p])]))`

**Comment by tanzoniteblack** [comment]
I would make a PR for this, but you don't seem to be able to make PR's for wikis

**Comment by nathanmarz** [comment]
There's a separate repo for the wiki, thanks https://github.com/nathanmarz/specter-wiki
