### ISSUE TITLE
Adding ^:const to precompiled path var causes exception when using it

### ISSUE THREAD

**Issue by NoamB** [nathanmarz/specter#28]
```
    (def ^:const y (spec/comp-paths [:a :b]))
    => #'dove.core.repl/y
    (spec/compiled-select-first y {:a {:b 1}})
    CompilerException java.lang.IllegalArgumentException: No matching field found: select-executor for      class com.rpl.specter.impl.ExecutorFunctions, compiling:... 
```

Without ^:const it will work properly.

Is this intentional or a bug?

**Comment by nathanmarz** [comment]
This looks like a bug. It appears to only happen with the ^:const metadata – I was not able to reproduce it with other metadata.

**Comment by nathanmarz** [comment]
I understand what's happening now. When you use :^const on a symbol, Clojure will inline that value wherever it's used. This is intended for simple values like numbers and strings, and doesn't work for a complex datatype that contains nested anonymous functions. What we're seeing here it the behavior of Clojure, so there's nothing to fix.
