### ISSUE TITLE
Trying to understand difference between `[ALL :a even?]` and `[ALL :a :b]`

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#3]
I've been writing some executable examples and have come across behavior I don't understand:

```clojure
  ;; The following can be read as "select all the even values of :a":
  (select [ALL :a even?] [{:a 1} {:a 2}]) => [2] 
  ;; Notice that the first map does not contribute to the output.

  ;; And then the following might be read as "select all the :b values of :a". 
  ;; But it is not.
  (select [ALL :a :b] [{:a "a"}
                       {:b "b"}
                       {:a {:b "ab"}}
                       {:a {:c "ac"}}]) =not=> ["ab"]
  ;; In this case, maps with an :a but without a :b DO contribute:
  (select [ALL :a :b] [{:a "a"}
                       {:b "b"}
                       {:a {:b "ab"}}
                       {:a {:c "ac"}}]) => [nil nil "ab" nil]

  ;; Why is that? Note that it's NOT that the last component is returning `nil` rather than `false`.
  (select [ALL :a #(if (even? %) true nil)] [{:a 1} {:a 2}]) => [2])
```

What am I missing?

**Comment by marick** [comment]
P.S. The executable-examples-as-documentation I'm writing is here: https://github.com/marick/specter/blob/master/examples/selecting.clj 

Because I'm thinking of using Specter for Midje's parsing in v2.0, I want to understand it well. Which means trying out examples. Which is more convenient to do by writing Midje tests that autotest in the repl runs for me immediately. And if I'm being systematic about it, I might as well add comments and make the documentation available to other people via a pull request.

Would such more files like the above be of interest?

**Comment by nathanmarz** [comment]
Perhaps this helps:

[ALL :a even?] can be interpreted as navigate to :a key of all elements, and only keep values that are even

[ALL :a :b] can be interpreted as navigate to :b key of :a key of all elements. In this case you get null values because the value of the :b key in those maps is nil.

Functions are treated as filters in Specter - if they return truthy the element is kept selected, otherwise it is removed from selected values.

You can see how keywords and functions are implemented as selectors here: https://github.com/nathanmarz/specter/blob/master/src/clj/com/rpl/specter.clj#L160

**Comment by marick** [comment]
Ah. I was thinking of keywords in their role as a callable.

Are you interested in my continuing to work on examples?

**Comment by nathanmarz** [comment]
Absolutely! More documentation is always helpful. Let me know if you need any more guidance.

**Comment by marick** [comment]
Given this:

```clojure
  (select [ALL FIRST] []) => []
  (setval [ALL FIRST] "never used" []) => []
```

I was surprised by the `update` below:
```clojure
  (select [FIRST ALL] []) => []
  ;; Given the results above, I would have expected an empty result for [], not [nil]
  (update [FIRST ALL] #(do (prn :called %) "never used") []) => [nil])
```

**Comment by nathanmarz** [comment]
I opened #4 to track this. Not sure at the moment what the behavior should be for selecting/updating with FIRST/LAST on empty collections, but I'm leaning towards throwing an error.
