### ISSUE TITLE
How do you compose select vectors?

### ISSUE THREAD

**Issue by bsima** [nathanmarz/specter#34]
Hey @nathanmarz - really loving specter, and I'm trying to learn it to get the most power out of it. In particular, I'm wondering if you could help me understand this bit of code I wrote. This function walks into a Clojure map `m`, collects all of the keywords, then filters for a particular key `k`, and counts all instances of `k`:

```clojure
(defn cardinality [m k]
  (first (select [(filterer (partial = k)) (view count)]
                 (select (walker keyword?) m))))
```

This works, but I have to call `first` and make two calls to `select`. When I try to compose the `select` vectors like this, I get back `IllegalArgumentException`:

```clojure
(defn cardinality-2 [m k]
  (select [(walker keyword?)
           (filterer (partial = k))
           (view count)]
          m))
```

Ultimately, after experimentation, I refactored to:

```clojure
(defn cardinality-3 [m k] (count (select (walker (partial = k) m))))
```

But I still don't understand why `cardinality-2` didn't work. I'm thinking that `walker` maybe doesn't compose like `filterer` and the other functions? The blog post and docs didn't really give me a good intuition about this in particular, so I was hoping you could help out when you have a chance.

**Comment by nathanmarz** [comment]
`walker` works like `ALL`: it navigates you to each of the elements it finds. So that means that you're passing to the `filterer` navigator individual instances of keywords, whereas filterer expects a sequence as input. I think the best way to make cardinality-2 work is like this:

```clojure
(defn cardinality-2 [m k]
  (count 
    (select [(walker keyword?)
             (partial = k)]
            m)))
```

**Comment by bsima** [comment]
Ah, makes sense now, thanks!
