### ISSUE TITLE
More vector examples?

### ISSUE THREAD

**Issue by jeaye** [nathanmarz/specter#36]
There are plenty of examples about working with map keys and vector indices (and ranges), but not many about working with values within vectors. My current issue is taking this:

```clojure
   [:declare-statement
    [:type
     [:function-type
      "ƒ"
      [:function-parameter-type [:type [:identifier "string"]]]
      [:function-return-type [:type [:identifier "string"]]]]]]
```

and turning it into (by running each `[:type ...]` sequence through `(get-in item [1 1])`):

```clojure
   [:declare-statement
      "ƒ"
      [:function-parameter-type "string"]
      [:function-return-type "string"]]
```

How would this be done with specter? I think there should be more vector-based examples, including:

1. An obvious replacement for `(get-in foo [0 1 1 ...])`
2. As described above, a way to walk and update vectors based on a given nth value

**Comment by jeaye** [comment]
I ended up using `postwalk` for this, and changed my data format expectations slightly to make things easier. I'd still like to see how to do this in specter and having more example relating to vectors would be lovely.

My `postwalk` with the same above input:
```clojure
(defn shorten-types [item]
  (clojure.walk/postwalk
    (fn [x]
      (if (and (vector? x) (= :type (first x)))
        (rest (second x))
        x))
    item))
```
and its output:
```clojure
[:declare-statement
 ("ƒ"
  [:function-parameter-type ("string")]
  [:function-return-type ("string")])]
```

**Comment by nathanmarz** [comment]
Specter has a walk selector that you can use for this, e.g.:

```clojure
(transform (walker (fn [v] (and (vector? v) (= (first v) :type)))) (fn [v] (rest (second v))) structure)
```
To navigate to specific indices, you can use `keypath`:

```clojure
(select (keypath 1) somevector)
```
