### ISSUE TITLE
selecting/filtering on vector indices

### ISSUE THREAD

**Issue by oborder** [nathanmarz/specter#37]
Hi,

I don't know if there is a better place to have a conversation about using specter so I am posting here.

I need to select and transform my data by filtering on vector indices. I don't know if it is already supported with the current api. As I could not find out how to do it, I have added filterer-indexed which takes two parameters similar to map-indexed (ix and item), I can submit them as I patch if this is desired, though the implementation simply copies existing filterer and filter+ancestry.

I have tried a few approaches. I have gotten furthest by by using a 3 step process

1. transforming data (using transformed and/or view) into [index item] vectors
2. filtering appropriate items
3. transforming data back to original shape (loosing index / second)

but this does not work correctly for transforms mainly because the transform back doesn't get applied for non selected items. So if for example i wan't to  for example i want to up-case the second item in a vector ["a" "b" "c"] I get a result of [[0 "a"] "B" [2 "c"]]...

**Comment by nathanmarz** [comment]
If you know the specific index you want to navigate to, you can just use `keypath`, like so:

```clojure
(transform (keypath 1) #(.toUpperCase %) ["a" "b" "c"])
```

As for the more general case of navigating to some or all of the elements and being able to make use of the index for the rest of the manipulation, you'd need to implement a new selector to make that work right. Here's something i whipped up quickly which works:

```clojure
(deftype AllIndexed [])

(extend-protocol StructurePath
  AllIndexed
  (select* [this structure next-fn]
    (mapcat next-fn (map-indexed vector structure)))
  (transform* [this structure next-fn]
    (->> structure
         (map-indexed vector)
         (map next-fn)
         (map last)
         doall
         )
    ))

(def ALL-INDEXED (->AllIndexed))
```

An example:

```clojure
(transform [ALL-INDEXED (selected? FIRST even?) LAST] inc [0 1 2 3 4])
(1 1 3 3 5)
```

It needs a little bit more work to make sure it maintains the sequence type.

**Comment by oborder** [comment]
Ok. Thanks for the info...
