### ISSUE TITLE
Returning sub-map with select, not value

### ISSUE THREAD

**Issue by LusciousPear** [nathanmarz/specter#45]
Hello! Been a while.

I'm writing some ETL code which basically filters a map by another map. Specter seems right for this. For example: 

    {:a 
      {:b {:c 4 :d 5} 
       :e {:f 6 :g 7} 
       :h {:i 8 :j 9} }}
    
    filter by [ [:a :b :c] [:a :e :f] ]
   
     ---> {:a 
            {:b {:c 4}}
             :e {:f 6}}

I think the main thing I'm not understanding is getting select to return a sub-map, instead of the value. For instance ```(select [ALL :a :b :c])``` returns ```"4"``` instead of ```{:a {:b {:c 4}}```.

What concept am I missing?

**Comment by nathanmarz** [comment]
Here's one way to write your function:

```clj
(defn filter-map [paths input]
 (reduce
   (fn [m p] (setval p (select-one p input) m))
   {}
   paths
   ))

(filter-map [[:a :b :c] [:a :e :f]]
 {:a 
  {:b {:c 4 :d 5} 
   :e {:f 6 :g 7} 
   :h {:i 8 :j 9} }})
=>  {:a {:b {:c 4}, :e {:f 6}}}
```

**Comment by LusciousPear** [comment]
Interesting -- I didn't think of building a new map instead of filtering the original. Thanks!
