### ISSUE TITLE
Protocol Issue when working with Specter and Om

### ISSUE THREAD

**Issue by drusellers** [nathanmarz/specter#46]
I'm getting the following error when trying to use specter to query my nested dictionary `No protocol method IReduce.-reduce defined for type om.core/IndexedCursor: [object Object]`

Pic of Stack Trace
![image](https://cloud.githubusercontent.com/assets/63355/12076110/f0ece3b0-b163-11e5-8304-5c47dbfbf889.png)

Query
`(s/select [:events s/ALL] the-comp)`

Full Code Sample

```clojure
(defn score-entry-widget [data owner]
  (om/component
    (print data)
    (let [the-comp (:competition data)
          event-id (:current-event data)
          measures (s/select [:events s/ALL] the-comp)]
      (html [:div {:class "score-entry"}
              [:div {:class "input"}
                (for [m measures]
                  [:label 
                    [:input {:type "text"}] 
                    [:span (:name m)]])]
              [:button "Submit"]]))))
```

Sample Payload of `the-comp`

```clojure
{:name "Fittest Games",
 :competitors
 [{:id 1,
   :name "Jeff Vanlandingham",
   :gym "CrossFit Jaakarhu",
   :division-id 1,
   :scores {1 {:value 20, :uom :sec}, 2 {:value 20, :uom :reps}}}
  {:id 2,
   :name "Reid Reagan",
   :gym "CrossFit Jaakarhu",
   :division-id 1,
   :scores {1 {:value 21, :uom :sec}, 2 {:value 21, :uom :reps}}}
  {:id 3,
   :name "Albert Leyva",
   :gym "CrossFit Dallas Central",
   :division-id 1,
   :scores {1 {:value 22, :uom :sec}, 2 {:value 22, :uom :reps}}}
  {:id 4,
   :name "Jeremy Kampen",
   :gym "CrossFit Jaakarhu",
   :division-id 1,
   :scores {1 {:value 23, :uom :sec}, 2 {:value 23, :uom :reps}}}],
 :divisions [{:id 1, :name "Mens Rx", :description ""}],
 :events
 [{:id 1,
   :name "Fran",
   :division-id 1,
   :priority :task,
   :measures
   [{:id 1,
     :name "Reps",
     :description "Total Reps",
     :sort :task,
     :conversion-factor 1}]}
  {:id 2,
   :name "Cindy",
   :division-id 1,
   :priority :time,
   :measures
   [{:id 1,
     :name "Reps",
     :description "Total Reps",
     :sort :task,
     :conversion-factor 1}]}]}
```

**Comment by nathanmarz** [comment]
I was unable to reproduce this on the sample payload you provided, but clearly from the stack trace the data structure you're operating on is not a regular clojure data structure. Based on the stack trace, I'm guessing that IndexedCursor is not compatible with clojure.core.reducers, which is what ALL uses underneath. 

Try this substitute for ALL and let me know how it goes:

```clojure
(defpath ALL2 []
  (select* [this structure next-fn]
    (doall (mapcat next-fn structure))
    )
  (transform* [this structure next-fn]
    (mapv next-fn structure)
    ))
```

**Comment by drusellers** [comment]
Your update has me working again. :) 

My code update:
```clojure
(ns app.client.score-entry
  (:require
   [om.core :as om :include-macros true]
   [app.util :as u]
   [com.rpl.specter :as s]
   [com.rpl.specter.protocols :as p]
   [sablono.core :as html :refer-macros [html]])
  (:require-macros [com.rpl.specter.macros :as d])
  )


(d/defpath ALL2 []
  (p/select* [this structure next-fn]
    (doall (mapcat next-fn structure))
    )
  (p/transform* [this structure next-fn]
    (mapv next-fn structure)
    ))

(defn score-entry-widget [data owner]
  (om/component
   (let [the-comp (:competition data)
         event-id (:current-event data)
         measures (s/select [:events ALL2] the-comp)]
     (print measures)
     (html [:div {:class "score-entry"}
            [:div {:class "input"}
             (for [m measures]
               [:label 
                [:input {:type "text"}] 
                [:span (:name m)]])]
            [:button "Submit"]]))))
```

Output:
```
[[{:id 1, :name Fran, :division-id 1, :priority :task, :measures [{:id 1, :name Reps, :description Total Reps, :sort :task, :conversion-factor 1}]}] [{:id 2, :name Cindy, :division-id 1, :priority :time, :measures [{:id 1, :name Reps, :description Total Reps, :sort :task, :conversion-factor 1}]}]]
```

Which I'm assuming is correct, and that I just need to do some extra processing to get my items out of the nested vectors and such. :)

Also, for reproducibility

```
  :dependencies [[com.rpl/specter "0.9.0"]
                 [org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.170"]
                 [cljsjs/react "0.14.3-0"]
                 [cljsjs/react-dom "0.14.3-1"]
                 [cljsjs/react-dom-server "0.14.3-0"]
                 [org.omcljs/om "0.9.0"]
                 [sablono "0.5.3"]]
```

**Comment by drusellers** [comment]
Also, the data that is being queried is coming from an `atom` ultimately. 

atom -> om/root -> widget [data owner] -> om/component -> (:competition data) -> then i run the `select`

Its highly possible I'm doing something idiotic as i'm new to Om.

**Comment by nathanmarz** [comment]
I'm confused – it's working now with ALL2, right? The reason ALL wasn't working is because Om's IndexedCursor doesn't implement the protocols that clojure.core.reducers requires.

**Comment by drusellers** [comment]
@nathanmarz sorry for the confusion. Let me see if I can write a test to highlight my issue. :)

**Comment by drusellers** [comment]
## Test Output

```
FAIL in (all-vs-all2) (competitions_tests.clj:18)
expected: (= all all2)
  actual: (not (= [{:id 1, :name "Fran", :division-id 1, :priority :task, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]} {:id 2, :name "Cindy", :division-id 1, :priority :time, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}] [[{:id 1, :name "Fran", :division-id 1, :priority :task, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}] [{:id 2, :name "Cindy", :division-id 1, :priority :time, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}]]))
```

## Just the payloads

```
[{:id 1, :name "Fran", :division-id 1, :priority :task, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]} {:id 2, :name "Cindy", :division-id 1, :priority :time, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}]
[[{:id 1, :name "Fran", :division-id 1, :priority :task, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}] [{:id 2, :name "Cindy", :division-id 1, :priority :time, :measures [{:id 1, :name "Reps", :description "Total Reps", :sort :task, :conversion-factor 1}]}]]))
 ^ the extra vector
```

## The test

```
(ns app.competitions-tests
  (:require [clojure.test :refer :all]
            [com.rpl.specter :as s]
            [com.rpl.specter.macros :as d]
            [com.rpl.specter.protocols :as p]))

(d/defpath ALL2 []
  (p/select* [this structure next-fn]
    (doall (mapcat next-fn structure))
    )
  (p/transform* [this structure next-fn]
    (mapv next-fn structure)
    )) 

(deftest all-vs-all2
  (let [all (s/select [:events s/ALL] app.competitions/a-competition)
        all2 (s/select [:events ALL2] app.competitions/a-competition)]
    (is (= all all2))))
```

**Comment by nathanmarz** [comment]
Define ALL2 like this:

```clojure
(d/defpath ALL2 []
  (select* [this structure next-fn]
    (doall (mapcat next-fn structure))
    )
  (transform* [this structure next-fn]
    (mapv next-fn structure)
    )) 
```

Since it's not finding select* and transform* (those exact symbols), it's getting nil for the select/transform functions, which is interpreted as navigating to current location. I'll open an issue to throw error when those symbols are improperly defined.

**Comment by drusellers** [comment]
@nathanmarz kaboom. that squared it away. Would this `ALL2` make its way back into the mainline application for us Om/React users or will we have to have a "custom" `ALL2`

**Comment by nathanmarz** [comment]
The better solution is for Om's data structures to be compatible with core.reducers. ALL is more efficient than ALL2 and also maintains the type of the data structure. You may be able to implement that compatibility yourself as I believe clojure.core.reducers is based on protocols.

**Comment by drusellers** [comment]
@nathanmarz roger that - thank you. :)

**Comment by drusellers** [comment]
@nathanmarz I opened an issue with Om and @swannodette suggested that Specter should support transducers rather than reducers. I readily admit I couldn't identify one from the other so I'm not sure what I'm suggesting here. Would it be possible for Specter to function with transducers rather than reducers? Based on http://clojure.org/transducers it seems (at least simplistically) that transducers are reducers minus the actual data to be reduced, and that it *might* be possible to make this happen.

Based *purely* on the `ALL2` I can see that `mapcat` has a transducer but `mapv` does not, so I could imagine that would be an issue given how Specter does such a great job with maintaining sequence types - but I could easily be missing the bigger picture.

I can see that [transduce](http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/transduce) was added in version 1.7 of clojure and that Specter is using CLJX to support an older version of Clojure so this work would have to be done when Specter is ok with only supporting 1.7+ of Clojure.

I have been very pleased with this project and how it has made my code easier to work with, and I'd like to help out however I can and allow others to use it with Om. Given that, my first question would is, would you accept work to bring Specter to 1.7+ support? I know this is not a small question since it would mean breaking current 1.6 compatibility, and rev'ing the project.

Thank you for all of your work.

**Comment by swannodette** [comment]
I did not suggest any changes to Specter which supports reducers likely for backwards compatibility. I suggested as Nathan did that *you* implement the reducers protocol in your own code on `IndexedCursor` :) Unsubscribing from this thread.

**Comment by drusellers** [comment]
My apologies, that is correct swannodette did specify **me** in his comment, I then interpreted that as, "if Specter could support them, then the community would benefit" and then came back to this issue. Therefore the suggestion to change is my own. Nathan as well suggested that I might be able to implement it myself, so I will dig in and take a look.

**Comment by nathanmarz** [comment]
Yea maintaining Clojure 1.6 compatibility is important, so we can't really use transducers inside Specter core. Your other option to having IndexedCursor implement the core.reducers protocol is to make your own version of ALL that uses transducers instead.

**Comment by drusellers** [comment]
@nathanmarz awesome, thank you for the update on 1.6 support :+1: and I'll look at both the core.reducers protocol with IndexedCursor and or building out my own ALL with transducers. Both seem bigger than I imagine they really are. Thank you again for your help. :)

**Comment by nathanmarz** [comment]
No problem. I don't think it will be very much code either way.
