### ISSUE TITLE
Add "locate" functionality

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#49]
This is an idea for major new functionality for Specter. Not all the details are worked out yet.

The idea is to have a new top-level function called "locate" that provides brand-new functionality on paths. This function would be as significant as "select" or "transform" and would add a new dimension to the library. "locate" returns paths to the individual elements found, and then those paths can be used to do further selection/manipulation. Here's a speculative example:

``` clojure
(def locations (locate [ALL :a ALL] structure))
(if (>= (count locations) 2)
  (->> structure
         (transform (first locations) inc)
         (transform (second locations) dec)))
```

The locations could also be introspected to know – in this case – which indices in the two sequences the locations correspond to. 

A "location" works like any other path but it can navigate back to itself in the data structure faster than using the general path that found it in the first place (for example, because it knows the specific indices in the sequence to jump to rather than do a scan). It is also specific. So you could have workflows that locate something of interest deep in the data structure, do further queries on that location along with retrieving relevant information from other sources, and then finally do a transformation on that location when all the info has been put together.

Implementation-wise, any Specter path statically implies what its location path will be. `[ALL :a ALL]`'s location path would be `[keypath :a keypath]` (minus working out some details about dealing with non-vector sequences). So the specific location is just a parameter list for those parameterized selectors.

**Comment by nathanmarz** [comment]
Specter how has recursive navigation which will affect the design of this feature.

**Comment by FeLungs** [comment]
Is there an ETA for this feature?

**Comment by nathanmarz** [comment]
No ETA as of now

**Comment by aengelberg** [comment]
Ideas for what protocols could provide the locate functionality:
```clojure
(locate* [this current-path structure next-fn]
  ;; current-path is a vector of navigators built up so far
  ;; current-path = [] at the top level
  (next-fn (conj current-path ...) (... structure)))
```
```clojure
(locate* [this structure next-fn]
  ;; must return a sequence of paths
  (map #(conj % ...)
    (next-fn (... structure))))
```
Sets could be an issue when working with `ALL`; how can you guarantee a path into a specific item from a set?
```clojure 
(let [data #{{:a 1} {:a 2 :b 3}}
      [p] (locate [ALL :a even?] data)]
  (->> data
       (transform p inc)
       (transform p inc)))
=> #{{:a 1} {:a 4 :b 3}}
;; how?
```

**Comment by nathanmarz** [comment]
So the tricky thing with this is that `locate` needs to return compiled paths, and it needs to do so efficiently. Returning an uncompiled path is straightforward but it will be slow to use those paths. That's what I was getting at in the original description with a location path being statically knowable from the navigation path. It seems that the fundamental operation of `locate` is generating an array of parameters for each location. Recursive paths and mutually recursive paths imply that the length of the parameters array can vary.

Regarding data structures like sets that don't have ways to point to a specific element, I'm not sure what the right approach would be. I'm leaning now towards throwing a runtime error for cases like that.

**Comment by nathanmarz** [comment]
A couple more thoughts:

1. Actually, sets do have a valid stable key, which is the value itself in the set.
2. Since a data structure can change and invalidate prior locations, there should be a way to determine if a location is still valid. So for something like navigating by key, this would work by un-intertwining the filtering logic that `must` does from its actual navigation.

**Comment by nathanmarz** [comment]
`keypath` seems like the natural location equivalent of `ALL`, but it doesn't translate to maps. I think this is evidence the current formulation of `ALL` is wrong and that for maps it should only navigate to the map values. Similarly, `ALL` on vectors doesn't navigate to pairs of index/value. 

For consistency and to enable the `locate` feature, `MAP-VALS` should be removed and `ALL`'s semantics should be changed. `ALL` should be renamed to `VALS`, and a new `KV-PAIRS` navigator should be added. Additionally, `VAL` should be renamed to something else to avoid confusion (`COLLECT-VAL`?).

**Comment by PetrGlad** [comment]
I mostly concerned with transparency of paths - e.g. for debugging or diagnostics. 
Having access to only compiled paths would obfuscate this and forces me to use Specter library with found paths also. On the other hand since found path is just a sequence of keys that I can feed to `get-in`, for example, is there a need for more optimizations?

**Comment by nathanmarz** [comment]
Decided not to add a `locate` implementation to the open source version of Specter. It's not really that useful anyway without a bunch of other functionality.
