### ISSUE TITLE
How can I transform the value at a specified key in a nested map?

### ISSUE THREAD

**Issue by nodename** [nathanmarz/specter#57]
The key may occur at any depth in the nested map structure. I can select the key with 
`(s/walker #(= % my-key))`
but how can I access its value to transform that, not the key?

**Comment by nathanmarz** [comment]
The code on master (not released yet) has the functionality you need:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(declarepath map-key-walker [akey])

(providepath map-key-walker
  [ALL
   (if-path [FIRST (paramsfn [akey] [curr] (= curr akey))]
     LAST
     [LAST (params-reset map-key-walker)])])

(select
  (map-key-walker :aaa)
  {:a {:aaa 10 :b {:c {:aaa 2} :aaa 1}}})
;; => [2 1 10]

(transform
  (map-key-walker :aaa)
  inc
  {:a {:aaa 10 :b {:c {:aaa 2} :aaa 1}}})
;; => {:a {:b {:c {:aaa 3}, :aaa 2}, :aaa 11}}
```

Using declarepath you can have a path refer to itself in its own definition. map-key-walker is defined as needing one parameter (which is used by the paramsfn that checks the key). params-reset indicates that at the point of recursion, it should use the params that were passed in at the top level.

This is pretty advanced Specter usage, so let me know if anything here needs more explanation.

**Comment by nathanmarz** [comment]
Also, this particular example only works on nested maps – it is not written to handle structures with other data structures involved. Using protocol paths or more usage of if-path / cond-path, other kinds of data structures could be handled.

**Comment by nathanmarz** [comment]
Actually, you can combine this with `walker` to get it to walk all data structure types:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(declarepath map-key-walker [akey])

(providepath map-key-walker
  [(walker map?)
   ALL
   (if-path [FIRST (paramsfn [akey] [curr] (= curr akey))]
     LAST
     [LAST (params-reset map-key-walker)])])

(transform (map-key-walker :aaa)
  inc
 [[{:aaa 2} {:a {:aaa 3}} 10] {:a {:b {:c 7}}} {:aaa 11}])
;; => [[{:aaa 3} {:a {:aaa 4}} 10] {:a {:b {:c 7}}} {:aaa 12}]

**Comment by nodename** [comment]
Thanks!

**Comment by johanhaleby** [comment]
I think this should be a first class construct. For example when selecting values from an xml datastructure it is often the case that you want to search for "nodes" with a specific name and return all its values (attributes, text and children in the case of xml).

**Comment by nathanmarz** [comment]
Specter addresses an endless amount of uses cases, not all of them should be made part of the Specter core library. I don't find this use case to be even close to as universal as compared with the navigators that come with Specter. It has always been intended that navigators tailored to a more specific use case be part of their own library – so if you were to make a specter.xml library, that's where it would make sense to include a navigator like map-key-walker.

**Comment by johanhaleby** [comment]
@nathanmarz Ok I'm convinced and you are absolutely right. I can definitely see that something like this would be useful in other areas besides xml so calling it "specter.xml" might not be the best name for such a lib (what would be?)? I briefly tried to copy your code into my project that used the latest _released_ version of specter but I couldn't get it working, is this because:

> The code on master (not released yet) has the functionality you need

? Unfortunately this made me switch to xpath and standard clojure functions instead for my particular case but I think specter would have made it easier to understand.

**Comment by RuthKelly** [comment]
This will only work if it never reaches a point where the value isn't a map. Is there a way to search a map recursively without this case breaking it? For example if the map changed to: {:a {:aaa 10 :b 1 :b {:c {:aaa 2} :aaa 1}}}, the first value of :b is 1 and not a map.

**Comment by nathanmarz** [comment]
@RuthKelly your example doesn't make sense:

```clojure
user=> {:a {:aaa 10 :b 1 :b {:c {:aaa 2} :aaa 1}}}

IllegalArgumentException Duplicate key: :b  clojure.lang.PersistentArrayMap.createWithCheck (PersistentArrayMap.java:70)
```

**Comment by RuthKelly** [comment]
@nathanmarz Sorry I didn't check that example. If I try this example:

(select
  (map-key-walker :b)
  {:a {:aaa 10 :b {:c {:aaa 2} :aaa 1}}})

I get the following error: Don't know how to create ISeq from: java.lang.Long
What I gather is it gets to :aaa 10 and then 10 isn't a sequence

**Comment by nathanmarz** [comment]
@RuthKelly I think you're trying the wrong code, as what I last showed works fine:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(declarepath map-key-walker [akey])

(providepath map-key-walker
  [(walker map?)
   ALL
   (if-path [FIRST (paramsfn [akey] [curr] (= curr akey))]
     LAST
     [LAST (params-reset map-key-walker)])])


(select
(map-key-walker :b)
{:a {:aaa 10 :b {:c {:aaa 2} :aaa 1}}})
;; => [{:c {:aaa 2}, :aaa 1}]
```

**Comment by findmyway** [comment]
```
user=> (declarepath map-key-walker [akey])

ArityException Wrong number of args (2) passed to: specter/declarepath  clojure.lang.Compiler.macroexpand1 (Compiler.java:6781)
```

Using the latest version (0.13.2)

**Comment by nathanmarz** [comment]
@findmyway 0.13.0 changed how Specter works significantly. For this example:

```
(def map-key-walker
  (recursive-path [k] p
    [(walker map?)
     ALL
     (if-path [FIRST #(= % k)]
       LAST
       [LAST p]
       )))
```
