### ISSUE TITLE
Creating a group-by path

### ISSUE THREAD

**Issue by caleb** [nathanmarz/specter#59]
**EDIT: I'd like to label this as a "question" but I don't know how to add labels to issues since I don't have the gear button on the right next to "Labels". Sorry about that.**

Hi,

I'm just starting to play with Specter (I'm using ClojureScript), and I am impressed at how simple the API is, and how easy it is to think in Specter.

I have data that I sometimes need to group-by multiple times:

```clojure
[{:type "person" :id "1"},
 {:type "person" :id "2"}]
```

grouped by `:type` and `:id` becomes

```clojure
{"person" {"1" {:type "person" :id "1"}
           "2" {:type "person" :id "2"}}
```

It seemed like I could write a `GROUP-BY` path for specter. Here is my first pass:

```clojure
(defpath GROUP-BY [f]
  (select* [this structure next-fn]
           (let [grouped (group-by f structure)
                 result (for [k (keys grouped)]
                          (let [v (get grouped k)
                                nv (next-fn v)]
                            [k nv]))]
             (into {} result)))
  (transform* [this structure next-fn]))

(def data {:entities [{:id "1" :type "person" :name "Joe"}
                      {:id "2" :type "person" :name "Bob"}
                      {:id "1" :type "robot" :name "Marvin"}
                      {:id "2" :type "robot" :name "Bender"}]})

(do
  (println "******************")
  (select [(GROUP-BY :type) (GROUP-BY :id) FIRST] (:entities data)))
```

(I use `FIRST` because group-by gives a map of keys to vectors, and i know that my groups will only have one element because I am grouping by a unique id)

It's almost working, but I am getting back vectors in the nested map:

```clojure
{"person" {"1" [{:type "person" :id "1"}]
           "2" [{:type "person" :id "2"}]}
```

If I don't use `FIRST`, then I get back a vector inside of another vector:

```clojure
{"person" {"1" [[{:type "person" :id "1"}]]
           "2" [[{:type "person" :id "2"}]]}
```

Using multiple `FIRST`s at the end of the path doesn't get rid of the final vector. Actually it returns the first map entry inside of a vector (e.g. `[[:type "person"]]`)

Is there a good way to do this? Or is what I'm going just plain wrong? :)

**Comment by nathanmarz** [comment]
`select` always returns a sequence of "found" elements, which is also the expectation of the next-fn within select*. So the way you're trying to use it just doesn't work.

All you really need is a path that navigates you to a grouped view of the sequence. Try this:

```clojure
(defpath group-by-view [key]
  (select* [this structure next-fn]
    (next-fn (group-by key structure))
    )
  (transform* [this structure next-fn]
    (next-fn (group-by key structure))
    ))

(def data {:entities [{:id "1" :type "person" :name "Joe"}
                      {:id "2" :type "person" :name "Bob"}
                      {:id "1" :type "robot" :name "Marvin"}
                      {:id "2" :type "robot" :name "Bender"}]})

(transform [:entities (group-by-view :type) ALL LAST (group-by-view :id)]
  identity
  data)
```

**Comment by nathanmarz** [comment]
You could also do the following to replicate what you were trying to accomplish with GROUP-BY:

```clojure
(def GROUP-BY (comp-paths group-by-view ALL LAST))

(transform [:entities (GROUP-BY :type) (GROUP-BY :id)] first data)
```

**Comment by caleb** [comment]
Thanks! I figured I was breaking a contract. And using transform makes more sense now that I see the solution.

Also just learned about comp-paths. Awesome
