### ISSUE TITLE
Non-LazySeq SetVal method?

### ISSUE THREAD

**Issue by StephenRudolph** [nathanmarz/specter#60]
Hi @nathanmarz et al!

Playing around a little with this library, it appears that `transform` and `setval` will return a `LazySeq` and `select` will return a `PersistentVector`. Does Specter provide any way of controlling the return collection type?

Thanks for your time and for your work!
  -Stephen

**Comment by nathanmarz** [comment]
`transform` and `setval` maintain the type of the input, so I don't know what you're referring to. Can you provide an example? Also, are you using Clojure or ClojureScript?

**Comment by StephenRudolph** [comment]
Ahh, wonderful! Then, this is just a matter of debugging. For reference I'm using Specter 0.9.1 and Clojure 1.8.0 (not ClojureScript). Here are some of my tests (run from the REPL) and their output:

Select (PersistentList becomes PersistentVector):
  (def select-test (com.rpl.specter/select [com.rpl.specter/ALL] '(1 2 3 4 5)))
  => #'clondike.core/select-test
  (type select-test)
  => clojure.lang.PersistentVector
  (pprint select-test)
  [1 2 3 4 5]

Transform (PersistentList becomes LazySeq):
  (def transform-test (com.rpl.specter/transform [com.rpl.specter/ALL] inc '(1 2 3 4 5)))
  => #'clondike.core/transform-test
  (type transform-test)
  => clojure.lang.LazySeq

SetVal (PersistentList becomes LazySeq):
  (def setval-test (com.rpl.specter/setval [com.rpl.specter/ALL] 1 '(1 2 3 4 5)))
  => #'clondike.core/setval-test
  (type setval-test)
  => clojure.lang.LazySeq

**Comment by nathanmarz** [comment]
`select` always returns a sequence of results and places no guarantees on the return type. 

If you run transform/setval on a vector, set, or map, you will get back the exact same type. With lists, the best it can do is return a resolved LazySeq as the result – which is functionally equivalent to lists in all the situations I can think of (e.g. semantics with conj).

**Comment by StephenRudolph** [comment]
That makes perfect sense - it looks like I managed to hit edge cases then. I originally noticed the LazySeq results not with lists, but with PersistentQueue, which is what I'm actually using in my code.

At some point, I may look into adding PersistentQueues to the list of types that transform/setval leave in place - if I do and I manage to get it working, would you be interested in a pull request from me?

Thanks for the explanation!
    -Stephen

**Comment by nathanmarz** [comment]
Yea, that would be a good case to get working properly. The relevant code is here: https://github.com/nathanmarz/specter/blob/master/src/clj/com/rpl/specter/impl.cljx#L506

Lists are handled specially because doing a clojure.core.reducers/map into an empty list actually reverses the order.

**Comment by StephenRudolph** [comment]
Thanks - I'll check it out then!
