### ISSUE TITLE
Get transform to only receive collect values

### ISSUE THREAD

**Issue by saulshanabrook** [nathanmarz/specter#61]
I have a data structure like this:

```clojure
    {:index 0
     :run-id run-id
     :individuals (repeatedly n (fn [] {:genome (->genome)
                                        :parents-ids []
                                        :id (utils/id)
                                        :traits {}}))}
```

And i have a function that generations the `:traits` from the `:genome`. 

I have it working like this:

```clojure
    (sp/transform [:individuals sp/ALL (sp/collect-one :genome) :traits]
      (fn [genome _] (genome->traits genome))
      generation)))
```

But I would like to remove that anonymous function that just discards the second argument (the old traits) and passes the genome on. Can I use tell transform somehow to not pass in the last values, just the collected ones? Or should I not be using transform here?

**Comment by nathanmarz** [comment]
That's correct, idiomatic usage of Specter. Adding an option like that would slow down transform for all use cases of it, which is absolutely not worth it. I find that example code you provided to be quite nice.

An alternative way to write it which you may prefer is this:

```clojure
(defn first-arg [arg & _] arg)
(sp/transform [:individuals sp/ALL (sp/collect-one :genome (view genome->traits)) :traits]
      first-arg
      generation)))
```

If you find yourself using that pattern a lot, you could factor it like this:

```clojure
(defn replace-with-collected-value [path structure]
  (transform path first-arg structure))

(replace-with-collected-value [:individuals sp/ALL (sp/collect-one :genome (view genome->traits)) :traits]
      generation)
```

**Comment by saulshanabrook** [comment]
Thanks @nathanmarz, the `view` option is an interesting alternative. 

I really appreciate this well designed library.
