### ISSUE TITLE
Select fails when selector returns nil somewhere

### ISSUE THREAD

**Issue by hugobessaa** [nathanmarz/specter#69]
I have a structure that isn't always completed. Sometimes it is lacking a key I wanted to select.

Trying to run:

```clojure
(s/select-one [s/ALL :a s/ALL :b]
              [{:c []}])
```
Throws an exception:

```
#object[Error Error: No protocol method IReduce.-reduce defined for type null: ]
```

I don't know if it is the desired behavior, but I was expecting that specter would behave like `get-in`, where it returns `nil` if any path doesn't match.

**Comment by hugobessaa** [comment]
For now, I'm protecting my selectors with `boolean`.

```
(s/select-one [s/ALL :a boolean s/ALL :b]
              [{:c []}])
```

**Comment by nathanmarz** [comment]
Yea, this has been a common problem in cljs since Specter currently relies on reducers to manipulate sequences in ALL, but cljs doesn't implement the reducers protocol for most things. Will try to have a fix for this in the next version.

**Comment by hugobessaa** [comment]
Thanks!

**Comment by nathanmarz** [comment]
This is now fixed in master.

**Comment by hugobessaa** [comment]
Awesome!
