### ISSUE TITLE
Transforming Map Keys Fails

### ISSUE THREAD

**Issue by alexanderkiel** [nathanmarz/specter#71]
I try to transform the keys of a map.
```clojure
(transform [ALL FIRST] name {:a 1})
```
should return
```clojure
{"a" 1}
```
but it throws a `ClassCastException`.

On the other hand the following works and transforms the value:
```clojure
(transform [ALL LAST] inc {:a 1})
;=> {:a 2}
```

Another approach using a walker works also on keys:
```clojure
(transform (walker keyword?) name {:a 1})
;=> {"a" 1}
```

But the walker approach replaces all keywords, not only keys on a specific layer.

Are there better ways to deal with nested maps were I want to transform things on a specific layer? Maybe the approach with `ALL`, `FIRST` and `LAST` is not the best way to do it.

**Comment by nathanmarz** [comment]
This is already fixed on master and will be released with 0.9.3.

**Comment by alexanderkiel** [comment]
Thanks!

**Comment by setzer22** [comment]
Was this fixed? I can replicate it using specter 0.13.2 (and also 0.9.3). This is the actual code (which keywordizes string keys in a json read string):

```
(defn load-json [json-str]
  (specter/transform
   [specter/ALL specter/FIRST]
   (fn [k] (keyword (str *ns*) (name k)))
   (json/read-str json-str)))

```

**Comment by nathanmarz** [comment]
This works fine for me:
```clojure
(transform [ALL FIRST]  (fn [k] (keyword (str *ns*) (name k))) {:a 1 :b 2})
```

What is the class of the object returned by `json/read-str`?

To look into this I'll need a test case I can reproduce. If you put up a repo with instructions on how to run it I can look into it.

**Comment by setzer22** [comment]
My bad, I am using maven and had the dependency listed in two different places. One with 0.9.2 and the other one with 0.13.2. Oddly enough maven took 0.9.2 and ignored the other version without complaining, but in any case this is not specter's fault.

Sorry for that!
