### ISSUE TITLE
Instead of having a separate function for compiled arguments, infer from the argument.

### ISSUE THREAD

**Issue by indigo0086** [nathanmarz/specter#74]
I recently watched the video and it's an amazing library.  One thing I noticed is that it seemed so simple to get an optimized version of some operations by using a compiled path and calling the compiled-*  function why not roll that into the main function and infer on if the argument is compiled and call the most optimized version.  Seemed there were three stages of optimization in two functions that I think can be easily made into two stages (inline path and compiled path) of optimization in one function.  Let me know if that makes sense.

**Comment by nathanmarz** [comment]
`select` and `transform` already do this. The compiled-* functions exist to eliminate the cost of checking whether it's compiled or not. In my presentation you can see a performance difference between calling select/transform with a compiled path vs. calling compiled-select/compiled-transform with a compiled path.
