### ISSUE TITLE
how to use walker in a longer navigation

### ISSUE THREAD

**Issue by pmwhite** [nathanmarz/specter#78]
I've got this expression that evaluates just fine.

    (select (walker hole?) test-data)

It obviously extracts all the items that satisfy `hole?` in the test data. I got this from the Readme.

Now, if I try to do 

    (select [(walker hole?) FIRST] test-data)

in order to get the first one, it doesn't work. I get

    Unhandled java.lang.IllegalArgumentException
    Don't know how to create ISeq from: clojure.lang.Symbol

I'm assuming I just don't know what I'm doing; this probably isn't a bug.

So how do I include `walker` in a longer navigation?

**Comment by nathanmarz** [comment]
`walker` is like ALL in that it navigates you to each element, not to a sequence of elements. Here's one way to do your example:

```clojure
(select-first (walker hole?) test-data)
```

`select-first` is just doing `(first (select ... ))` underneath.

In the next release, there's a new navigator called subselect which lets you navigate to the sequence selected by a path, and transforms to those elements are applied back where the elements came from in the original sequence. For example:

```clojure
(transform [(subselect (walker number?)) FIRST] inc test-data)
```

This increments the first number found during the traversal done by `walker`. If you want to use `subselect` before the next release, you can just copy the implementation from specter.cljx.

**Comment by pmwhite** [comment]
Ahhh, thank you. Subselect is indeed what I'm looking for, because I also want to use transform.
