### ISSUE TITLE
[Question] Expanding a vector

### ISSUE THREAD

**Issue by mantree** [nathanmarz/specter#82]
I can't figure out how to replace an element in a vector with multiple elements. The most basic version of what I'm after would look like:

``` clojure
(transform [ALL #(= 2 %)]
           (constantly [3 3])
           [1 2 3]) => [1 3 3 3]  ; obviously the actual return value is [1 [3 3] 3]
```

I've tried all sorts of things to get what I'm after, but none of them worked (although it's been a good learning experience). I just started thinking that a new kind of 'transform' is needed, an 'expand' if you will, but I thought I'd better check that I wasn't missing something before setting off on that adventure.

Is there a way to get this working?

**Comment by Misophistful** [comment]
Does this do what you want?
```clojure
(setval (srange 1 2) [3 3] [1 2 3])

**Comment by mantree** [comment]
Well that answers the question I've posed, but my real problem is a bit more complicated, trimmed it down too far perhaps.

A more accurate snippet would be:

```clojure
(transform [ALL (selected? LAST #(= % :b))]
           (constantly [[:x :x] [:y :y]])
           [[:a :a] [:a :b] [:c :c]]) => [[:a :a] [:x :x] [:y :y] [:c :c]] ; actual [[:a :a] [[:x :x] [:y :y]] [:c :c]]
```

The position of the [:a :b] tuple within the sequence is unknown and I want to replace it with two new tuples.

**Comment by Misophistful** [comment]
I can't figure out how to do what you want, so I'm also very interested to hear Nathan's response.

It seems like using `END` allows for the type of expansion you're looking for:
```clojure
(setval [END]
        [[:x :x] [:y :y]]
        [[:a :a] [:a :b] [:c :c]])
=> [[:a :a] [:a :b] [:c :c] [:x :x] [:y :y]]
```
But not when you navigate to a particular element:
```clojure
(setval [ALL (selected? LAST #(= :b %))]
        [[:x :x] [:y :y]]
        [[:a :a] [:a :b] [:c :c]])
=> [[:a :a] [[:x :x] [:y :y]] [:c :c]]
```
I think this might be to do with how END actually navigates to an empty vector, so when that empty vector gets replaced it behaves like an "expand", but I'm not certain.

**Comment by mantree** [comment]
Yeah, it's fiddly. I thought i'd like a new kind of transform, but realise now that would defeat the purpose a bit. With a little more understanding I'm wondering if a new REPLACE path might do it, but that obviously a terrible name. I do need a transform here, as the content of the new nodes depends on the current one.

My actual use case is manipulating onyx workflows, which are DAG's represented by tuples in a vector, something like:

```clojure
[[:input :inc][:inc :dec][:dec :output]]
```

What I want to achieve is to insert another step, have :input go somewhere else and have :inc take from there:

```clojure
[[:input :mult][:mult :inc][:inc :dec][:dec :output]]
```

I can do this with two transforms, but I'd really like a way to do it in one. A custom path seems in order at the moment.

**Comment by nathanmarz** [comment]
You can do this with the new zipper navigators in 0.10.0, but it will be more efficient and easier with a new navigator. You need something like ALL, but instead of navigating to each individual element it should navigate to every one element subsequence. Then the results of the subvalue transformations should be concatenated together. 

The navigator roughly looks like this:

```clojure
(defpath ALL-ELEM-SEQ []
  (select* [this structure next-fn]
    (mapcat (fn [e] (next-fn [e])) structure)
    )
  (transform* [this structure next-fn]
    (mapcat (fn [e] (next-fn [e])) structure)    
    ))

(transform [ALL-ELEM-SEQ (selected? FIRST even?)]
  (fn [[e]] (repeat e e))
  [1 2 3 4 5])
;; (1 2 2 3 4 4 4 4 5)
```

More work is necessary to get the transform case to maintain the type of the input sequence.

**Comment by mantree** [comment]
Thanks Nathan!

I'll give this a whirl tomorrow, should reduce my number of transformations nicely.

**Comment by aengelberg** [comment]
I can think of another way to solve this using the built-in `parser` navigator:

```clojure
(setval [(parser #(map vector %) #(reduce into [] %))
         ALL
         (selected? FIRST #(= % 2))] ; or use even? etc.
        [3 3]
        [1 2 3])
```

**Comment by eyston** [comment]
Anyone have an `ALL-ELEM-SEQ` in 0.11.0 style?  I just picked up specter last night so I'm a bit new, but this is functionality I could use (I want to move children to siblings -- this should allow that).  Thanks~
