### ISSUE TITLE
Question on removing from nested vector

### ISSUE THREAD

**Issue by vitalyper** [nathanmarz/specter#83]
Given nested structure below how can I remove **:sub-id "s1"**

```
{:joe
 ["sessionobj"
  [{:sub-id "s1", :cpair "c1"} {:sub-id "s2", :cpair "c2"}]]}
```

so I will get 

```
{:joe ["sessionobj" [{:sub-id "s2", :cpair "c2"}]]}
```

**Comment by nathanmarz** [comment]
This will be useful to you: https://github.com/nathanmarz/specter/issues/82#issuecomment-215098107

With this path, you can write this transformation as:

```clojure
(setval [:joe LAST ALL-ELEM-SEQ (selected? FIRST :sub-id #(= % "s1"))]
  []
  data)
```

The new zipper navigators in 0.10.0 can also be used to accomplish this transformation:

```clojure
(setval [:joe LAST VECTOR-ZIP DOWN NEXT-WALK (selected? NODE :sub-id #(= % "s1")) NODE-SEQ]
  []
  data)
```

**Comment by vitalyper** [comment]
Thanks Nathan,

The first attempt failed as it could not find path **ALL-ELEM-SEQ** neither in 0.9.3 nor 0.10.0.

But the zipper one worked in 0.10.0.

**Comment by mattiasw2** [comment]
Cannot find ALL-ELEM-SEQ in 0.13.2

So, any pointers on how this should be done now?

**Comment by nathanmarz** [comment]
With 0.13.3-SNAPSHOT you can do this:

```
(setval [:b ALL nil?] NONE {:a 1 :b [1 2 nil 3 nil]})
;; => {:a 1 :b [1 2 3]}
```
