### ISSUE TITLE
Working with namespaced keywords

### ISSUE THREAD

**Issue by levitanong** [nathanmarz/specter#85]
Say you have a shape like so:

``` clj
[{:a/a 1 :a/b 2}
 {:b/a 3 :b/b 4}
 {:c/a 5 :c/b 6}]
```

How do you collect the keywords regardless of namespace?

**Comment by nathanmarz** [comment]
I'm not clear on what you're trying to do. What's the output you want to receive?

**Comment by levitanong** [comment]
Apologies for the ambiguity. This is the output I'd like to receive:
``` clj
[1 3 5]
```

I'd imagine the solution would involve something that looks like:
```
(defn ignore-keyword-ns [k]
  (keyword (name k)))
(select [ALL ignore-keyword-ns]
  [{:a/a 1 :a/b 2}
   {:b/a 3 :b/b 4}
   {:c/a 5 :c/b 6}])

**Comment by nathanmarz** [comment]
There's no way to do this without scanning over all the keys. You can do this with this path:

```clojure
(select [ALL ALL (selected? FIRST (view name) #(= "a" %)) LAST]
  [{:a/a 1 :a/b 2}
   {:b/a 3 :b/b 4}
   {:c/a 5 :c/b 6}]
  )
```

**Comment by nathanmarz** [comment]
You can factor out "ignoring a key's namespace" as its own reusable navigator like this:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(def ignore-key-ns
  (comp-paths
    ALL
    (selected?
      FIRST
      (view name)
      (paramsfn [target] [n] (= n (name target))))
    LAST
    ))

(select [ALL (ignore-key-ns :a)]
  [{:a/a 1 :a/b 2}
   {:b/a 3 :b/b 4}
   {:c/a 5 :c/b 6}]
  )
```

**Comment by levitanong** [comment]
Thanks for your answer! This seems to be exactly what I need. What does `view` exactly do? It doesn't seem to be documented in `specter.cljx` or the readme.

**Comment by nathanmarz** [comment]
It navigates to the result of running that function on that value.

**Comment by levitanong** [comment]
Got it. Thanks, man :D
