### ISSUE TITLE
[Question] How to do nothing if a path selects nothing?

### ISSUE THREAD

**Issue by tslocke** [nathanmarz/specter#86]
Inc the last item within key `:a`

    (s/transform [:a LAST] inc {:a [1 2 3]})
    => {:a [1 2 4]}

What if there is no `:a`?

    (s/transform [:a LAST] inc {:b [1 2 3]})
    => {:b [1 2 3], :a nil}

How would I get `{:b [1 2 3]}`? i.e. nothing changes.

**Comment by nathanmarz** [comment]
This has come up a few times and is a reasonable use case, so I added a navigator for it: https://github.com/nathanmarz/specter/blob/master/src/clj/com/rpl/specter.cljx#L282

```clojure
(transform (must :b) inc {:a 1})
;; => {:a 1}

(transform (must :a) inc {:a 1})
;; => {:a 2}
```

**Comment by tslocke** [comment]
Just to understand better - was there way to do this already, and `must` is just a convenience?

**Comment by nathanmarz** [comment]
The only way to replicate the semantics of `must` would have been something like this:

```clojure
(transform [#(contains? % :a) :a] inc DATA)
```

There's no way to define `must` as the composition of the other navigators.
