### ISSUE TITLE
walker of nested maps only finds 1st occurence

### ISSUE THREAD

**Issue by maacl** [nathanmarz/specter#90]
New to specter so this might just be me who is confused, but I would have expected the below to find all maps with a ```:c``` key ie ```{:a 1, :b {:c 2}, :c "test"} {:c 2})```, but I only get the first hit:

    (select (walker :c)  {:a 1 :b {:c 2} :c "test"})
    > ({:a 1, :b {:c 2}, :c "test"})

walker does walk the structure as shown by:

    (select (walker :c)  {:a 1 :b {:c 2} :d "test"})
    > ({:c 2})

**Comment by nathanmarz** [comment]
That's the correct behavior of `walker`. It walks until reaching something matching that predicate. Here's how to define a walker that continues walking after matching a value:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)

(declarepath MapKeyWalker [match-fn])
(providepath MapKeyWalker
  [walker
   (continue-then-stay
     ALL LAST (params-reset MapKeyWalker))])

(select (MapKeyWalker :c) {:a 1 :b {:c 2} :c "test"})
;; => ({:c 2} {:c "test", :b {:c 2}, :a 1})
```

**Comment by maacl** [comment]
Ok, but how is that consistent with:

    (select (walker number?)
              {2 [1 2 [6 7]] :a 4 :c {:a 1 :d [2 nil]}})
    > [2 1 2 1 2 6 7 4]

Again sorry if I am missing something obvious here.

**Comment by nathanmarz** [comment]
By "walk until" I don't mean "stop on the first match in the structure". I mean "stop on values that match the function". So, for example:

```clojure
(select (walker :c) {:a {:c 1} :b {:c 2} :d {:e 1}})
;; => ({:c 2} {:c 1})
```
