### ISSUE TITLE
[Question] Storing value for later reuse in select

### ISSUE THREAD

**Issue by mtruyens** [nathanmarz/specter#91]
Hi, 

First of all, many thanks for your excellent library! 

Suppose I have the following map:

```clojure
{:tabs [{:id 1 :value "A"} {:id 2 :value "B"}]
:active-tab 2}
```
I would now like to select the tab whose :id is equal to :active-tab. 
Is it possible to do so in one select query, or do you always need two queries for this (because you essentially walk down one level to :active-tab, then need to go up again, and then one level down again for :tabs)? 
If not possible in one go, then it would be great if you could store the result of a subselect (perhaps even as a kind of "named variable"?) in order to later on reuse it.

**Comment by nathanmarz** [comment]
Sorry for being so late on responding. Somehow this slipped by me.

Currently you would need to do two selections.... though in theory Specter is all set up to be able to do something like this. With `collect-one` you can capture values to be used by the transform-fn at the end, or in the case of selection to be part of the return. Navigators don't currently expose a way to access those collected values even though internally they're passing them around. I'll leave this issue open as I think about how such functionality might be exposed and whether that's a good idea.

**Comment by nathanmarz** [comment]
Found a pretty elegant solution to this, with the new features required now in master. With the next release, the code to solve your problem looks like this:

```clojure
(def data
  {:tabs [{:id 1 :value "A"}
          {:id 2 :value "B"}]
   :active-tab 2})

(select [(collect-one :active-tab)
         :tabs
         ALL
         (collect-one :id)
         (collected? [a i] (= a i))
         DISPENSE]
        data)
;; => [{:id 2, :value "B"}]
```

The `collected?` macro creates a filter function that takes in the collected values as input. The `DISPENSE` navigator drops all collected values for subsequent navigation (which in this case prevents the collected values from being part of the return).

**Comment by mtruyens** [comment]
Awesome, thanks!
