### ISSUE TITLE
[Request] Summary of what is new/fixed in 0.10.0

### ISSUE THREAD

**Issue by AngryGami** [nathanmarz/specter#92]
Specter is great. It really helps me with my everyday tasks. Its previous release was more than year ago and now it is new and shiny version available though I kinda eager to know what actually was done at least maybe major stuff if any. Please. :)

**Comment by nathanmarz** [comment]
There's been almost 20 releases since Specter was released. All the changes are listed in the changelog at https://github.com/nathanmarz/specter/blob/master/CHANGES.md
