### ISSUE TITLE
Speed up map navigation

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/specter#95]
Coercing MapEntry to vector was probably a mistake due to slowing things down for no real benefit. If this is done KEY and VAL navigators would have to be added for accessing the MapEntry – and the current VAL navigator renamed (probably to COLLECT-VAL). Also, using reduce-kv for doing ALL over a map may provide performance improvement.

**Comment by nathanmarz** [comment]
reduce-kv for transforms implemented for 0.11.1 for Clojure version

**Comment by nathanmarz** [comment]
After some investigation almost all the current overhead is in the calls to `last` and  `impl/set-last`. Fast implementations for these may be possible, or the MapEntry strategy can be pursued

**Comment by aengelberg** [comment]
Could you just implement the `GetExtremes` and `UpdateExtremes` protocols on `clojure.lang.MapEntry`? Or change `(extend-protocol UpdateExtremes clojure.lang.PersistentVector` to `(extend-protocol UpdateExtremes clojure.lang.IPersistentVector`.

**Comment by nathanmarz** [comment]
@aengelberg Good idea, I went ahead and did that

**Comment by nathanmarz** [comment]
After optimizing `update-last` for small vectors and making a `fast-empty?` protocol that directly checks size for vectors, the performance has been increased by more than 2x for basic use case of `(transform [ALL LAST] ...)`

**Comment by nathanmarz** [comment]
@aengelberg Had to change UpdateExtremes back to PersistentVector because it returns PersistentVector. The other protocols still extend IPersistentVector

**Comment by nathanmarz** [comment]
#100 will help with this issue as well

**Comment by nathanmarz** [comment]
These optimizations are done. Made the following changes for this issue:

- ALL transform uses a protocol to use an optimal implementation for each type
- PersistentArrayMap uses reduce-kv
- PersistentTreeMap uses reduce-kv
- PersistentHashMap uses reduce-kv + transients

The usage of a type-specific handler also eliminated the call to "empty".
